const impactWhey =
  "https://www.amazon.com/Myprotein-Impact-Protein-Salted-Caramel/dp/B06XC8TC79/ref=sr_1_1?crid=28FWB8QE6ELWE&dib=eyJ2IjoiMSJ9.x4Z-H8lQK85Q6L7CThu8zm6Q4lTuoH7dZf-yKc2kWhMETHX4BB2Nz0buj7xRuhXEYulF9ZjBcR3YbFip9oivpLnE7kjVIYtUE5MnYhMbBvaTAN2G_tAoFI_NUHTFeEwsym8Sy38BJ_z50Wv0fGxwM-eiGrSMpJsrJiZBMSMItJgzFHg9ivW8LQvsFav3KAQ-.ULUx5YEgbkNUVxaoNha0FYNYKlC7gWv81AdwoJdaMIo&dib_tag=se&keywords=myprotein+whey+isolate&qid=1718617169&sprefix=isolate+my%2Caps%2C193&sr=8-1";
const dymatizeIso100 =
  "https://www.amazon.com/Dymatize-Hydrolyzed-Absorbing-Digesting-Servings/dp/B099J2SWXV/ref=sr_1_2?crid=H22X36FJKB3Z&dib=eyJ2IjoiMSJ9.I-S4OXPqprrRhNM7Vq_o4uzzoymDGALXx5IpOMWo0g0Dcqa_VOhEnGRqnWNDzlt6bJDe34MRepr2TOvygS0AUiXrwpT2slhuEDwdVhPvrKSqcG6l1ybChieNioeC6Yw6ine844_JKc7uctrMoohYHiE82ndWNtLc4_JiLgxNPN3bfc40zJJHEnB6hIxYU4vmY8m35qQvhwihXrnJ7PuoGx71FD2ujyAYBojAn3yX9xNDQkQuOJLDs45sI3br3nr2Q7eDWh0BkfpPn-Fzc57gGjR3UbYRofCikSSZsaAJXuA.77ZFZKysMvZ7ughd5NnBvQLezkhcvu3GEM9vO1YHtW8&dib_tag=se&keywords=isolate+protein+powder&qid=1718617327&sprefix=isol%2Caps%2C185&sr=8-2";
const goldStandardIso =
  "https://www.amazon.com/Gold-Standard-100-Whey-Isolate/dp/B07G8BM32L/ref=sr_1_1?crid=H22X36FJKB3Z&dib=eyJ2IjoiMSJ9.I-S4OXPqprrRhNM7Vq_o4uzzoymDGALXx5IpOMWo0g0Dcqa_VOhEnGRqnWNDzlt6bJDe34MRepr2TOvygS0AUiXrwpT2slhuEDwdVhPvrKSqcG6l1ybChieNioeC6Yw6ine844_JKc7uctrMoohYHiE82ndWNtLc4_JiLgxNPN3bfc40zJJHEnB6hIxYU4vmY8m35qQvhwihXrnJ7PuoGx71FD2ujyAYBojAn3yX9xNDQkQuOJLDs45sI3br3nr2Q7eDWh0BkfpPn-Fzc57gGjR3UbYRofCikSSZsaAJXuA.77ZFZKysMvZ7ughd5NnBvQLezkhcvu3GEM9vO1YHtW8&dib_tag=se&keywords=isolate+protein+powder&qid=1718617327&sprefix=isol%2Caps%2C185&sr=8-1";

const dymatizeEliteCasein =
  "https://www.amazon.com/Dymatize-Absorbing-Overnight-Digesting-Chocolate/dp/B002SG7NDQ/ref=sr_1_1?crid=1491ZR2FXRY9Z&dib=eyJ2IjoiMSJ9.zsmlgP0nx-i-1ihs-Zxz7Mkhe8v_-9KWrsgd7HMHiJNTYdK28VKAJ8JIz4RS0vltj3OfL1MWZQ9jJM9st7IDM62B9IHMb1ZY70favYeQkNqqlfiJVidnT_02Ru8JchUOiLSZPMMMfn3RMcJE9VLrCJ4FeQcMbgP7SDbQU5E1CJupTdDwco3Zyf3T6wbPr2yUAOw4UkuPgOHcqY6J46ne57YeHrlb--Od2olJhzg8_ElvnHyKXYlOoOzy__17iPq63EmVoUMFqUSvGKlH3nHHKkV_jPCRFS9-_0SR19lYdc0.Q3W8BvosD8aeTP53OiYosxhXcs-geO9QPvTpO8ILdVI&dib_tag=se&keywords=casein+protein+powder&qid=1718617469&sprefix=casein+protein+powder%2Caps%2C227&sr=8-1";
const allmaxCaseinFX =
  "https://www.amazon.com/ALLMAX-Nutrition-Casein-FX-Slow-Release-Chocolate/dp/B004Z56032/ref=sr_1_3?crid=1491ZR2FXRY9Z&dib=eyJ2IjoiMSJ9.8cnHtZt1ypNquKQ5CR_0a7CuH8zOjRujjncKJbDGbio_-3WrStCPU1-waJ4YA5WNR2OWMZ6JaFpIWea0dEFdBrOGp6SsoIz0rNO8vuwjUy5MfezJ6K8bf8lOphL8IHt4I9Rkebom2fv5lzn_8mFsUwClFUJx4g68MD78kRLTlEev6JIJsXDaF0d7eg2YuGU5dw_rLlMZLwgpVZm60JMdx3HSEkK9YNICXWJZ-sBSzmel1HeGQ0zgN8gbd8oIyQVg3xAJT-Qz4aR7nfpESmNOrlOdcCHWwOnu5shbPuIINa0.jx3mioZZ0UZjY9D2EgSgk8eY8O7wHTuEjmzSg7Lp_jw&dib_tag=se&keywords=casein+protein+powder&qid=1718617700&sprefix=casein+protein+powder%2Caps%2C227&sr=8-3";
const muscletechPhase8 =
  "https://www.amazon.com/Muscletech-Platinum-Multivitamin-Vitamins-Supplements/dp/B0CSDCMD3Z/ref=sr_1_17?crid=1491ZR2FXRY9Z&dib=eyJ2IjoiMSJ9.8cnHtZt1ypNquKQ5CR_0a7CuH8zOjRujjncKJbDGbio_-3WrStCPU1-waJ4YA5WNR2OWMZ6JaFpIWea0dEFdBrOGp6SsoIz0rNO8vuwjUy5MfezJ6K8bf8lOphL8IHt4I9Rkebom2fv5lzn_8mFsUwClFUJx4g68MD78kRLTlEev6JIJsXDaF0d7eg2YuGU5dw_rLlMZLwgpVZm60JMdx3HSEkK9YNICXWJZ-sBSzmel1HeGQ0zgN8gbd8oIyQVg3xAJT-Qz4aR7nfpESmNOrlOdcCHWwOnu5shbPuIINa0.jx3mioZZ0UZjY9D2EgSgk8eY8O7wHTuEjmzSg7Lp_jw&dib_tag=se&keywords=casein+protein+powder&qid=1718617700&sprefix=casein+protein+powder%2Caps%2C227&sr=8-17";

const collagenBestForWomen =
  "https://www.amazon.com/Multi-Collagen-Pills-Types-III/dp/B07PYQJBH3/ref=sr_1_5?crid=2MWM4B0I7UDQ2&dib=eyJ2IjoiMSJ9.bfiOjxz7VYUjIf_aJKckUqlUdcMd4ftgM_rJMPJzvWb38sbh-WM90pIrNlezPQ6bjGoy7KVev7A2ZNSbkdQAo9oBkF0cqsOIDssryLX40q8N3sqcVJYjTwPh_Lt4JEXG5NO-L2o19ivNhN9g27R8gyN59zEsXAIz0YETgGk3HjUnRQ2VHldBKGTG_DYAVMhXGq6BnjqL9CWQaLqfSAjHiuhkASsOiS7rYUWDu8JjZIZph5h5cEbL13d1c7xS2elRM_Qdtmm3nKALK9A74qt1KQ6uPvaNJANt080qSI3lVvI.SaRg0vyL03wPzN7XP0hBQMaeCx0KJlpiidHUhI3qoKo&dib_tag=se&keywords=collagen&qid=1718618025&sprefix=collagen%2Caps%2C197&sr=8-5";
const vitalProteinsCollagen =
  "https://www.amazon.com/Vital-Proteins-Unflavored-Collagen-Peptides/dp/B07H85ZDLG/ref=sr_1_8?crid=1TREYCGT2QYTI&dib=eyJ2IjoiMSJ9.bfiOjxz7VYUjIf_aJKckUqlUdcMd4ftgM_rJMPJzvWb38sbh-WM90pIrNlezPQ6bjGoy7KVev7A2ZNSbkdQAo9oBkF0cqsOIDssryLX40q8N3sqcVJYjTwPh_Lt4JEXG5NO-L2o19ivNhN9g27R8g4oh7ce4Agclm0cl89dTSphrIVVfJQYSnlRChfRbgLDCGq6BnjqL9CWQaLqfSAjHiuhkASsOiS7rYUWDu8JjZIZqJqV3Z-7CSIDlxntTLXpv-slGiqKcWVaUA8uFAea4pw6uPvaNJANt080qSI3lVvI.IIAUQ8l7O47218jjPhogPZZJzWcA3H4cIxGuzVS1yZU&dib_tag=se&keywords=collagen&qid=1718618332&sprefix=collagen%2Caps%2C181&sr=8-8";

const allmaxAminoCoreBCAA =
  "https://www.amazon.com/AMINOCORE-BCAA-Branch-Chained-Pineapple/dp/B084KSPLXC/ref=sr_1_21?crid=EFX7WR1QMFYJ&dib=eyJ2IjoiMSJ9.4ZcavcqdTWuOYa6JpAa8Nj8qjp4G18FZRt_0pFSZ9B8e_DOVGb2mZz-QQ4uMUolFG4vf0NhuSorfdNoiDThn1piPtCq30dDL0mS2bXMkZ3NHI-tnN4g6_Ty92sidwdaT_jX897TGHB-8U_s681Pd2tyRa_OxR642Tq5Wzz3ZqjtPTfoUKYKlh2rOPSDj99gDc8JdcFFW7EMS41XFOjF1skskpQwGdTn1JjVxv8BQvFmyjCAbEnBCVxwc7JU2kSBlxxaw41BKwtn9lT17-z1Y2hvq0TKsEWL-vdvBD1grvgw.LUNu7-ZMQbZ3se0BuO9nSKXjxVsm9II6aoFJmEuFQbE&dib_tag=se&keywords=bcaa&qid=1718618601&sprefix=bcaa%2Caps%2C191&sr=8-21";
const ONaminoEnergy =
  "https://www.amazon.com/NUTRITION-ESSENTIAL-Raspberry-Preworkout-Essential/dp/B005Q8IM6K/ref=sr_1_1?dib=eyJ2IjoiMSJ9.-UWSyQOYivi-2p4q_q6Cgv-pfJpGV0ZQDdiNTT4iuEEJGSA4WuWlTLMx1Et8CSRXHJ4Z8T7Vmf-SpF84xJBBjAtJepzjMGCTUFZ06TFSVP-TVXDrNe6zFC4PsS-NJmyPq2LUyz0ZgJObf_XQHNzzJ6vg8q-7XhAxANEFtrWa9BcHS9v0dvhFFU6DxP8dfXch-hdzu8EtdY6UzTD8nMvs2whCioHooHhqdlKWmRQgVPpaAs3TvN2rh7s1wtLA_B8dWS-P9FAv2fEc0r_txUd8HYOgbYcwrRx6XxUQn0zhL3I.6wuN2NkLZhAKWf_nMSMT2rQGQoW0fe51SwhVLHrzMpg&dib_tag=se&keywords=bcaa&qid=1718618762&refinements=p_123%3A232507%7C250393&rnid=85457740011&s=hpc&sr=1-1";

const centrumMultivitaminForMen =
  "https://www.amazon.com/Centrum-Multivitamin-Multimineral-Antioxidants-Ingredients/dp/B09BW24R2B/ref=sr_1_1?crid=2IWW6CBNEACAC&dib=eyJ2IjoiMSJ9.nSgUPhosJJcKp37XEHh2C_OlcfjRbfWwpfPc0jku-y1D837gBF73B5QuGDI5LwalZFZrsR2hqeSyWWVteUL75ldfmJ161UGb4hO2Zx-8DohqHZCR2QRkxMzboGZXiCT1VZxL8RRrCweyFD8d7jtjKEamdMzhSU6lwGIDh7AhrISYDU3PIXT8Nslb0UVYu97TETFTO6ZkV4b2I1O8wgZNIf5JS_B5kVt77ZsgBnteLUlpACY_PIk-mEJFadWSC5rDDIBoaQIsZPLlN083KdP2ZXxONYVxWF0q3lmsB2Wkttg.fKmIpXxq2cnOdJP3ZygUlrwtpaOu8erFDLX3hNM27CA&dib_tag=se&keywords=multivitamin&qid=1718618929&refinements=p_123%3A223578%7C250393&rnid=85457740011&s=hpc&sprefix=multivitamin%2Caps%2C208&sr=1-1&th=1";
const centrumMultivitaminForWomen =
  "https://www.amazon.com/Centrum-Multivitamin-Multimineral-Antioxidant-Ingredients/dp/B09NNWPC52/ref=sr_1_3?crid=2IWW6CBNEACAC&dib=eyJ2IjoiMSJ9.nSgUPhosJJcKp37XEHh2C_OlcfjRbfWwpfPc0jku-y1D837gBF73B5QuGDI5LwalZFZrsR2hqeSyWWVteUL75ldfmJ161UGb4hO2Zx-8DohqHZCR2QRkxMzboGZXiCT1VZxL8RRrCweyFD8d7jtjKEamdMzhSU6lwGIDh7AhrISYDU3PIXT8Nslb0UVYu97TETFTO6ZkV4b2I1O8wgZNIf5JS_B5kVt77ZsgBnteLUlpACY_PIk-mEJFadWSC5rDDIBoaQIsZPLlN083KdP2ZXxONYVxWF0q3lmsB2Wkttg.fKmIpXxq2cnOdJP3ZygUlrwtpaOu8erFDLX3hNM27CA&dib_tag=se&keywords=multivitamin&qid=1718619044&refinements=p_123%3A223578%7C250393&rnid=85457740011&s=hpc&sprefix=multivitamin%2Caps%2C208&sr=1-3";

const ONmicronizedCreatine =
  "https://www.amazon.com/Optimum-Nutrition-Micronized-Monohydrate-Unflavored/dp/B002DYIZEO/ref=sr_1_1?crid=3RZQ3GX925C2K&dib=eyJ2IjoiMSJ9.GG8o4F9No6Xk1ypzEFsZ10L2hXFaPtnGYqmfr8_ogEPXifXRuN0ypbbwruCBYVfu04SvQeLx7xpl89XTdRWmRG1vS9uktDp5q2YnTi6B-ej82735xvTbJbowzotPQ1cd-kFyV8XfmJEe_m_VQoADwyfpdnM5egKqj1BCL1G1lMYK-9T1KVas3VUhHdjovDa7187wDKrYTKNk-A_FjgcwDi_fu3Xdg2XAHcfXZHgBlCgfq0MMsiVCKtgM2BV5GLwJ5FHQmGFi9hd_-IQOBEiAhucTY3KX3YZZBpc9zMrzYDc.j4iXEPQhcw1u8POkxQf3zQ6v0MvIb3nGQHNzRu53QL0&dib_tag=se&keywords=creatine&qid=1718619130&sprefix=cre%2Caps%2C199&sr=8-1";
const allmaxMicronizedCreatine =
  "https://www.amazon.com/ALLMAX-Nutrition-Creatine-Monohydrate-Powder/dp/B0043YJZNC/ref=sr_1_8?crid=3RZQ3GX925C2K&dib=eyJ2IjoiMSJ9.GG8o4F9No6Xk1ypzEFsZ10L2hXFaPtnGYqmfr8_ogEPk-opV_J40msQFwEQa_ujRuyUv73RlMEDXC08KHPoOxeN6dw4dxxGGD6mUStPtsLH82735xvTbJbowzotPQ1cdoW6hPdu3FAXVQW-ob0tFr79ZpEWsqmVNW-qEBro5935NpZchWmg6MjxyjEzGgHV3187wDKrYTKNk-A_FjgcwDkgkyp_JAp5neoa40txpNEpabfbd55bg_IUhaMnSpgbQ5FHQmGFi9hd_-IQOBEiAhvXkYjpxfFfylmpA13GYamU.Vxyvc4xEYSIKDEYCs3QElZyNXm_PvPfovzoiOqiwbeU&dib_tag=se&keywords=creatine&qid=1718619224&sprefix=cre%2Caps%2C199&sr=8-8";

const NOWfoodCarnitine =
  "https://www.amazon.com/NOW-Carnitine-Tartrate-1000mg-Tablets/dp/B00IXX1668/ref=sr_1_4?crid=28F0JXETU62LV&dib=eyJ2IjoiMSJ9.Ykxk_Y3YufMJqt47jyn8uVW-TWcr1JCErVv_ZHMOXZCf_Xdu7v36S0mlVOD5JKMVDubHBxT5x9Yma6OEGQuxipuOEDx930Mfbb6dMOrrMvpUYakXmWGnIQKfBuve3Cp3ni3qaNF_f3hD62wGs_A70gQkIMF5tGHctEwjsdK3FQFLFu3LVVRjXBml_dhkN3gCMAdjpXcTarZodpP-uC9AA2XLo3qi87Utiz1gfaEPvwCtAn5m8XF2Lq9OT2iNHZQOUKms7Ug1c9DuB-Sg9IMMr0LWlsV8cjJwxj5GEDoF-2g.GNzkOK5rEgKXWj3iZEE0zPmNFM-bxlD9JYL1XpDN2v4&dib_tag=se&keywords=carnitine&qid=1718619386&sprefix=carnitine%2Caps%2C211&sr=8-4";
const NOWsportsCarnitine =
  "https://www.amazon.com/Sports-Nutrition-L-Carnitine-Strength-16-Ounce/dp/B0019LVGPW/ref=sr_1_1?crid=28F0JXETU62LV&dib=eyJ2IjoiMSJ9.dif9oSVs7EQNa8Lr1m39oMjRNsVK-wEXhtfTD72UkRd6HII9BYde-SGIjC2OhCdp26I3DtJ0AHlrCiVFtj1qCA.RFM3Efee8HR9ntpI2PvJF4D4CrwNsdeUnu2kuzuazLo&dib_tag=se&keywords=carnitine&qid=1718619551&refinements=p_n_feature_eleven_browse-bin%3A23975216011%2Cp_72%3A1248903011&rnid=1248901011&s=hpc&sprefix=carnitine%2Caps%2C211&sr=1-1";

const NOWfoodArginine =
  "https://www.amazon.com/NOW-Foods-L-Arginine-1000mg-Tablets/dp/B00L83XT6A/ref=sr_1_3?crid=BE6U2Z0WBG5C&dib=eyJ2IjoiMSJ9.mc4EYYMPz4UN-ObZypw9cyGtUQIC1NAq8AGTkl_b8vZARclMO6SPWJhYpzCBWmedsS9J2dgmT3Md0MQm2TOKM6-9we2p4sWlgPDHFGinQ5Kn5snxaF_ltKct2d-GlxcTshr3f1ursu2VmwEuVOuzaUOoacW-UBjPzpxdYW-S2ljNOMR9Y5sKjdXZqu0iSirNtgyCmq3fzH-XAdFhLn2r9vo_tkABx2lkvyDitOSUY8zJgDAzajuO3CwJiC8dNS7x_gSJbhyn0De8cBL_7IyBFlP74Jy-vBxLX63y_cOVBX0.egXBaMpyr2_lmQDK2KroCvRCVThkurdsBswdDISBRPw&dib_tag=se&keywords=arginine&qid=1718619664&sprefix=arginine%2Caps%2C200&sr=8-3";
const drEmilArgininePlus =
  "https://www.amazon.com/Dr-Emils-ARGININE-Plus-Citrulline/dp/B07P6P2VQ9/ref=sr_1_1?crid=BE6U2Z0WBG5C&dib=eyJ2IjoiMSJ9.mc4EYYMPz4UN-ObZypw9cyGtUQIC1NAq8AGTkl_b8vZARclMO6SPWJhYpzCBWmedsS9J2dgmT3Md0MQm2TOKM6-9we2p4sWlgPDHFGinQ5Kn5snxaF_ltKct2d-GlxcTshr3f1ursu2VmwEuVOuzadiVRBA1pjhcPhULT-UHxhMy5-gv7CuF9povSRhXQS4X-_e4zFbOP8yKc21UXBxkZTDk7ijsgoDAu4MwhzXl8IOUdmXeC43bpZgJxWO5Q3FBwGVsYQEQRxBuY8UzSoGSruCP9X9GZZXHgo7MIXztr98.0GTPki62riSLVphCh9_YI0Ue6TP55cV9yzbaM-1zJ3Q&dib_tag=se&keywords=arginine&qid=1718619769&sprefix=arginine%2Caps%2C200&sr=8-1";

const allmaxAlanine =
  "https://www.amazon.com/ALLMAX-Nutrition-Beta-Alanine-14-11-400/dp/B003NZE0OG/ref=sr_1_2?crid=3QC3VVF30WGB6&dib=eyJ2IjoiMSJ9.zxDAxjrMxekWj1h2hgNVR4k3cdndEbN8ywq34y-o3A2DY2QP4vChjIMf2ltn90frMlIWZbrW5q5aEw58FI7qDt2YdqnGxMU93YdwDHFsHotHusHTEtHJjPeBY3MQk9hvNlHqHgjPHaLGex3IciO2ey6dsceHXrTok3wsKk-ZRnf89eARr1N7CVxdWmBPJYpigIp_TPTPqB5rLkcHDC_mt9HtZHVxQCqSZ69VrAOYFoSElR4KOQeXDWmGLrQJ6oofPs8dQBZuj5M-MIcrGU-gI94R5dC7vVLi89nMaBTGpfc.rwOOHOSTz6r_YYDjmaZjt4qE-zvab41tFc-uxjk2hjQ&dib_tag=se&keywords=alanine&qid=1718620015&sprefix=alanine%2Caps%2C194&sr=8-2";
const GNCalanine =
  "https://www.amazon.com/GNC-4332489524-Pro-Performance-Beta-Alanine/dp/B06X9KHFXG/ref=sr_1_3?crid=3QC3VVF30WGB6&dib=eyJ2IjoiMSJ9.zxDAxjrMxekWj1h2hgNVR4k3cdndEbN8ywq34y-o3A2DY2QP4vChjIMf2ltn90frMlIWZbrW5q5aEw58FI7qDt2YdqnGxMU93YdwDHFsHotHusHTEtHJjPeBY3MQk9hvNlHqHgjPHaLGex3IciO2ey6dsceHXrTok3wsKk-ZRnf89eARr1N7CVxdWmBPJYpigIp_TPTPqB5rLkcHDC_mt9HtZHVxQCqSZ69VrAOYFoSElR4KOQeXDWmGLrQJ6oofPs8dQBZuj5M-MIcrGU-gI94R5dC7vVLi89nMaBTGpfc.rwOOHOSTz6r_YYDjmaZjt4qE-zvab41tFc-uxjk2hjQ&dib_tag=se&keywords=alanine&qid=1718620138&sprefix=alanine%2Caps%2C194&sr=8-3";

const allmaxGlutamine =
  "https://www.amazon.com/ALLMAX-Nutrition-Pure-Micronized-Glutamine/dp/B000SSR976/ref=sr_1_4?crid=20UM9YB6S8Y9Y&dib=eyJ2IjoiMSJ9.HBiHouFoCLKKBHizHUkX0L_NzRFVveLvnvuTXEUbkHSNK0q9Z9TIMdd28cn8i0kZzXZf8RDvt8SshSi2pz9y4XPs59M4eRBymfgEBbTD_Pb6oUpcDj7e57juAs2ZMsRMoNGO-PVzTiqZSrCIbpexRxy6pIJPbq_-TJs7o3LFiQhKxrDwdnYeshFuEMuD5hmm_POuvr9sBj031WHdCp6KUFPFXT0qS8nps9jVzWfDxnuMO5dHKJewRsUE8O9l2PrwJd-c6uySjaN1UexhlajC-mqFuN6BlP_SD5hZyEKmHlg.EcZqLH1gZvxXophadSsr8oGoRJnurDua8cRxYfoLEus&dib_tag=se&keywords=glutamine&qid=1718620220&sprefix=glutamin%2Caps%2C189&sr=8-4";
const GNCglutamine =
  "https://www.amazon.com/GNC-Pro-Performance-L-Glutamine/dp/B01MZ54FUH/ref=sr_1_1?crid=271ZQMY54FDCG&dib=eyJ2IjoiMSJ9.BzO2LNmyMCDC7GIUL1Ghqk05u1DiMB8OZeaRRPsJnihUs7BpLKUeyLllpBTfHkngln0nibVBgtMqmF7PD9SN1A.u6rGpc2Urlel1x5UYJTzgLGqQ_vFHua0j1mif4GRA34&dib_tag=se&keywords=optimum+nutrition+l+glutamine&qid=1718620331&sprefix=glutamine+opti%2Caps%2C188&sr=8-1";

const NOWfoodGlucosamine =
  "https://www.amazon.com/Supplements-Glucosamine-Chondroitin-Strength-Sulfate/dp/B0013OQKQU/ref=sr_1_7?crid=12CLYCYA3XZH2&dib=eyJ2IjoiMSJ9.PMp8Yfe2M52poto6H-L18yw_IcUvb7_8gp5taX9ACH1Ac8PBitrqyQEIbp1K7xyAY51I_Ux24YLpxdHSAlEOe6OdezxcJPExftM4duYvMSB8qztmEVXIUsJozAcMuB6KgfxqYoykii5sbvTtAVuRZToeGR5b9S5MSnM9qp6zlYqjhTaW5mcy1jkGICD9-9myd74jDYyLq6tmAkrIzGkoqYd62ikc0Ql8IS2A7fT-5vxbFoj1f3LXYsZ4IM8rzSAwXakhfFrUlHEHgklX40SJQKxkjppfzwE5n-MnPxVj7Vc.enhOgVDs0J-mJwfnEVRWTRqcpP9NegAdC2JzVNzUcfk&dib_tag=se&keywords=glucosamine&qid=1718620460&sprefix=glucosamine%2Caps%2C196&sr=8-7&th=1";
const EVLglucosamineFormula =
  "https://www.amazon.com/Evlution-Nutrition-Glucosamine-Chondroitin-Turmeric/dp/B079RLFSMW/ref=sr_1_6?crid=1NBPKRADWKALY&dib=eyJ2IjoiMSJ9.QZDfUzAj5hWDB2XV3KQcVR1RZdc_9qtV6ouLocuOFkx3gLkV6aNcGP-fi79_xxce3MIEl9x9fZe3pFFAKfRFrG9VJ0lmlAAp9CCwPUTknfkMrRjJtvPFQhvL_bOfe1VH-WYoEhisHywgiuyeEkjVUC5cX9EE4kP7MQoth_kgdToPJzz0l5flwInE57W_ebRIV_K9i6enzcCLSNkmrR2_KqTiw9H2f-iHC-ZYan-JzDLyT_xV0l1fSkDZ0sYjFiKCaxdebFJTNWOSfjtMgkvj2G-oNlW3NIW2RLg3cTw0JzI.lhXD0rSkvbK0gDZkSqSU8QVk1gmc1Oe0q8SFtGuZNRE&dib_tag=se&keywords=glucosamine&qid=1718620625&sprefix=glucosamine%2Caps%2C177&sr=8-6";

const EVLleucineFormulaBCAA =
  "https://www.amazon.com/EVL-BCAAs-Amino-Acids-Powder/dp/B01M6ZO8DG/ref=sr_1_10?crid=2DGGKNZ1HFKCT&dib=eyJ2IjoiMSJ9.-NO9T16UB7Eny47ne9QjQBeL2MZyNDLQpowzD--6UGncz6LyukNA1Dw8x66DHUOR8OQA-Voms9Ibpsgm2bOU_bmxm9w4NBDR25JBcPIt-IBVnHmeMnmIGMErdWIlraz_GUZ6Q4qo1ffrwTqSlrfoRSd9jK3QYUOrLEHUV1cgSK97kT-M3RBmMYsx2rbtbtDb6nnjXWQchlWe7ICSJiDFQQ_pzD4cB7xJdJazTMKyT_kzAR0IY2BWgU4Ng-hmU7PdiSQOmy1GReFwyuGC-X2B_90xsi1ISiOKkGytkLrKoKM.X1GpFPTjMIqZXzF1-WhfbtGWKrCYzlEc54LhBTlTGSk&dib_tag=se&keywords=leucine&qid=1718620819&sprefix=leucine%2Caps%2C204&sr=8-10";
// const allmaxAminoCoreBCAA = "https://www.amazon.com/AMINOCORE-BCAA-Branch-Chained-Pineapple/dp/B084KSPLXC/ref=sr_1_21?crid=EFX7WR1QMFYJ&dib=eyJ2IjoiMSJ9.4ZcavcqdTWuOYa6JpAa8Nj8qjp4G18FZRt_0pFSZ9B8e_DOVGb2mZz-QQ4uMUolFG4vf0NhuSorfdNoiDThn1piPtCq30dDL0mS2bXMkZ3NHI-tnN4g6_Ty92sidwdaT_jX897TGHB-8U_s681Pd2tyRa_OxR642Tq5Wzz3ZqjtPTfoUKYKlh2rOPSDj99gDc8JdcFFW7EMS41XFOjF1skskpQwGdTn1JjVxv8BQvFmyjCAbEnBCVxwc7JU2kSBlxxaw41BKwtn9lT17-z1Y2hvq0TKsEWL-vdvBD1grvgw.LUNu7-ZMQbZ3se0BuO9nSKXjxVsm9II6aoFJmEuFQbE&dib_tag=se&keywords=bcaa&qid=1718618601&sprefix=bcaa%2Caps%2C191&sr=8-21";

const NOWfoodLysine =
  "https://www.amazon.com/NOW-Foods-L-Lysine-1000mg-Hydrochloride/dp/B0BTS1KGQG/ref=sr_1_5?crid=1B3COQMKFGRUH&dib=eyJ2IjoiMSJ9.G8SIBjb9tUsr3r3sr82o8rKrI35TbdMgYPuW0VErkAq9Co5pwlqNCawzo89RM3lU5oCYo1WoWVbYiPqohEqNWTf_EDBQumM5zf0t01rBPvnWZIUVIHssiWQVM2jMskXvFeiDX0UHnLU38xDpWgnLnvpwYzjkG2NIhsZkczOg3AGig-7dLQadYwFhCJ_h0cfuaD073BrZF5HA47I_Y23duZNpwVAshvD7Wt9khxpFYlTRsetop_DCFFtKMKDlFJ7030GRp1Ou8cWMguv7vpDFN5EHGk71_b83kRSEUdrrBk4.Uf5rYomBb4VqPk4N6bNa0xgYeezHy64fYDyQWyxWs88&dib_tag=se&keywords=lysine&qid=1718620980&sprefix=lysine%2Caps%2C260&sr=8-5";
const BronsonLysine =
  "https://www.amazon.com/Bronson-L-Lysine-Defense-Support-Complex/dp/B08B8W6BRK/ref=sr_1_2?crid=1B3COQMKFGRUH&dib=eyJ2IjoiMSJ9.G8SIBjb9tUsr3r3sr82o8rKrI35TbdMgYPuW0VErkAq9Co5pwlqNCawzo89RM3lU5oCYo1WoWVbYiPqohEqNWTf_EDBQumM5zf0t01rBPvnWZIUVIHssiWQVM2jMskXvFeiDX0UHnLU38xDpWgnLnvpwYzjkG2NIhsZkczOg3AGig-7dLQadYwFhCJ_h0cfuaD073BrZF5HA47I_Y23duZNpwVAshvD7Wt9khxpFYlTRsetop_DCFFtKMKDlFJ7030GRp1Ou8cWMguv7vpDFN5EHGk71_b83kRSEUdrrBk4.Uf5rYomBb4VqPk4N6bNa0xgYeezHy64fYDyQWyxWs88&dib_tag=se&keywords=lysine&qid=1718621032&sprefix=lysine%2Caps%2C260&sr=8-2";

const JamiesonVitaminB1 =
  "https://www.amazon.com/Jamieson-Vitamin-Thiamine-100-tablets/dp/B00CP7Q2EE/ref=sr_1_2?crid=34BOSTWJNY4MY&dib=eyJ2IjoiMSJ9.CQxLxGJ4ke1KSWrfodnkIyOlQ9z7AohuiVc58Ah6qdTzuc3mGhztFSsXoJmKISvyW7U1wyaHLX3hbFyM9m-d1ZfDOaKhk0OstR0vWfxAEGPojGtmkNeOe4EPVPiv55eIUrPoAqsi-wWgFmD26s0WOSNAsVUuy8hiT7JD6U0IewTRG5hQSV_r8oy3IF7DeMXY32h7PWhaNg39JlH4gYbbYs5vp-9kzn9jqeBY80LsDZ6fV78TqgWPOUooRIPU7MA0MqTXm3rNbMS5wiLMYFTYxeNvcQvgTYFoIoV3uTjxvZg.zRUramNrb4oCqggkpwLd_gVH-fFKCQHu472E3NMPGgQ&dib_tag=se&keywords=vitamin+B1&qid=1718621140&sprefix=vitamin+b1%2Caps%2C207&sr=8-2";
const GNCVitaminB1 =
  "https://www.amazon.com/GNC-Vitamin-B-1-300mg/dp/B00D036MAG/ref=sr_1_1?crid=34BOSTWJNY4MY&dib=eyJ2IjoiMSJ9.CQxLxGJ4ke1KSWrfodnkIyOlQ9z7AohuiVc58Ah6qdTzuc3mGhztFSsXoJmKISvyW7U1wyaHLX3hbFyM9m-d1ZfDOaKhk0OstR0vWfxAEGPojGtmkNeOe4EPVPiv55eIUrPoAqsi-wWgFmD26s0WOVOxCKp8RLz3MCBfM35tJQnWtmOJwt3GPdMpz3Sp-A7F32h7PWhaNg39JlH4gYbbYjWpkviap2tGnA9q9pQT7KQoY34BC1D1rkKlZVK2exveq1pKhCbq1HU3yPoAvNf03y1ZkGvKtJs7Cv7ERKgF1T4.cB2hnY5_z2OZYuNRXbA6KI4Om66LaH5HfmYaZ4y_BA8&dib_tag=se&keywords=vitamin+B1&qid=1718621211&sprefix=vitamin+b1%2Caps%2C207&sr=8-1";
// const divineBountySuperBcomplex = "https://www.amazon.com/Super-Complex-Vitamins-Supplement-Vegetarian/dp/B07414752B/ref=sr_1_4?crid=JBN0MFGHK3X2&dib=eyJ2IjoiMSJ9.9Z9dOHvFslhnaNDysP2LwG6zwpcDUSZuOmUClUDXgnvZppL1B4MSptQ2ItRDzaMykoq0rIaHDBFBOWavaqdgP-QKkKSpXoMlRD3bN5l-a8iMBw0GN92p1llOSwzPGmth2Gz-rdzudfyvEWoTDScbbL9nr_BLFCCWQ5H1B1QDXRKo2bCKTX9GonKGfvX8wadBAdYbFHhVZwtbJedVdCEgRJFim3NR2xTV-ZpADztIjoAg-vZUozlG6DHlkibNNx9weYYIgbvMkoz1vTDXmLZz_9urcS3xFw9aXnU__jDTU5k.NpUkRNNJZc4FY4ve55oAbNx5C3FaWQBVQAXbYmVdq1s&dib_tag=se&keywords=vitamin+B2&qid=1718621375&sprefix=vitamin+b2%2Caps%2C195&sr=8-4";

const NOWfoodVitaminB2 =
  "https://www.amazon.com/NOW-Vitamin-riboflavin-100mg-Capsules/dp/B001F0R94O/ref=sr_1_1?crid=JBN0MFGHK3X2&dib=eyJ2IjoiMSJ9.9Z9dOHvFslhnaNDysP2LwG6zwpcDUSZuOmUClUDXgnv--FxmcGiTkdipEk9lS9WGX7SXAklB3UxINs7-Bs3JucDSTXrscoyXmy5emybPrMQRVKKdqnoEXI4NXAr2AB-SfbLz95D4MZd0RqbJ7iH9Cr9nr_BLFCCWQ5H1B1QDXRK1-kh5z2M7U0vv0Sr7VQc5o-jyvCQTlOajNpu62O7I-IKqgOsZ6ggm23a4F1_t6SVCNMXEA30c6fb36587SdHBsH7TOVQf5Ykc6bOMu2Z4Vzr-qwJRjsegNgkxkpdNB-0.J_rhcnnOjKroHNiah2wCY8sPsXY_Zdho7cpL5Wn-XVo&dib_tag=se&keywords=vitamin+B2&qid=1718621313&sprefix=vitamin+b2%2Caps%2C195&sr=8-1";
// const divineBountySuperBcomplex = "https://www.amazon.com/Super-Complex-Vitamins-Supplement-Vegetarian/dp/B07414752B/ref=sr_1_4?crid=JBN0MFGHK3X2&dib=eyJ2IjoiMSJ9.9Z9dOHvFslhnaNDysP2LwG6zwpcDUSZuOmUClUDXgnvZppL1B4MSptQ2ItRDzaMykoq0rIaHDBFBOWavaqdgP-QKkKSpXoMlRD3bN5l-a8iMBw0GN92p1llOSwzPGmth2Gz-rdzudfyvEWoTDScbbL9nr_BLFCCWQ5H1B1QDXRKo2bCKTX9GonKGfvX8wadBAdYbFHhVZwtbJedVdCEgRJFim3NR2xTV-ZpADztIjoAg-vZUozlG6DHlkibNNx9weYYIgbvMkoz1vTDXmLZz_9urcS3xFw9aXnU__jDTU5k.NpUkRNNJZc4FY4ve55oAbNx5C3FaWQBVQAXbYmVdq1s&dib_tag=se&keywords=vitamin+B2&qid=1718621375&sprefix=vitamin+b2%2Caps%2C195&sr=8-4";
// const bronsonSuperBcomplex = "https://www.amazon.com/Bronson-Vitamin-Complex-Sustained-Release/dp/B0CT5Y3XK2/ref=sr_1_4?crid=1NPKMKYRTSY7W&dib=eyJ2IjoiMSJ9.m_TqrBrkrihtgJ2xMnA1_xHba7egjoUN3RxCCdSOmteiw3nW5uJcV7tdNo6HdRB-Q6gjDDoKmvf9X_Q1lNE-UdhKScgHHImWIfesNlAw1MKvH99JTPkVqTutNXJOgE1C_0i1LjndvAC7EwOrzut2092zseeB57oUEBeWONwcxWgO6UWDuhmUpExL_3LXHoxsWxEDBYzNeS0LxeWxNmVZIbMq-lm1XHFfkRq8reXPsbdGgnmii9Cj47KRDTqZYeUe4ENDu9DJBxLuocBWDpLjBpMkTaqQq9MRBd9j2U571gA.Te2iJcx7TtblOCju9KC0zA3982_OHapFKW6dta5a8r4&dib_tag=se&keywords=vitamin+B3&qid=1718621682&sprefix=vitamin+b3%2Caps%2C203&sr=8-4";

// const divineBountySuperBcomplex = "https://www.amazon.com/Super-Complex-Vitamins-Supplement-Vegetarian/dp/B07414752B/ref=sr_1_4?crid=JBN0MFGHK3X2&dib=eyJ2IjoiMSJ9.9Z9dOHvFslhnaNDysP2LwG6zwpcDUSZuOmUClUDXgnvZppL1B4MSptQ2ItRDzaMykoq0rIaHDBFBOWavaqdgP-QKkKSpXoMlRD3bN5l-a8iMBw0GN92p1llOSwzPGmth2Gz-rdzudfyvEWoTDScbbL9nr_BLFCCWQ5H1B1QDXRKo2bCKTX9GonKGfvX8wadBAdYbFHhVZwtbJedVdCEgRJFim3NR2xTV-ZpADztIjoAg-vZUozlG6DHlkibNNx9weYYIgbvMkoz1vTDXmLZz_9urcS3xFw9aXnU__jDTU5k.NpUkRNNJZc4FY4ve55oAbNx5C3FaWQBVQAXbYmVdq1s&dib_tag=se&keywords=vitamin+B2&qid=1718621375&sprefix=vitamin+b2%2Caps%2C195&sr=8-4";
const NOWfoodVitaminB3 =
  "https://www.amazon.com/Foods-Niacinamide-Vitamin-Capsules-100-Count/dp/B00N8425O4/ref=sr_1_5?crid=1NPKMKYRTSY7W&dib=eyJ2IjoiMSJ9.m_TqrBrkrihtgJ2xMnA1_xHba7egjoUN3RxCCdSOmteiw3nW5uJcV7tdNo6HdRB-Q6gjDDoKmvf9X_Q1lNE-UdhKScgHHImWIfesNlAw1MKvH99JTPkVqTutNXJOgE1C_0i1LjndvAC7EwOrzut2092zseeB57oUEBeWONwcxWgO6UWDuhmUpExL_3LXHoxsWxEDBYzNeS0LxeWxNmVZIbMq-lm1XHFfkRq8reXPsbdGgnmii9Cj47KRDTqZYeUe4ENDu9DJBxLuocBWDpLjBpMkTaqQq9MRBd9j2U571gA.Te2iJcx7TtblOCju9KC0zA3982_OHapFKW6dta5a8r4&dib_tag=se&keywords=vitamin+B3&qid=1718621602&sprefix=vitamin+b3%2Caps%2C203&sr=8-5";
// const bronsonSuperBcomplex = "https://www.amazon.com/Bronson-Vitamin-Complex-Sustained-Release/dp/B0CT5Y3XK2/ref=sr_1_4?crid=1NPKMKYRTSY7W&dib=eyJ2IjoiMSJ9.m_TqrBrkrihtgJ2xMnA1_xHba7egjoUN3RxCCdSOmteiw3nW5uJcV7tdNo6HdRB-Q6gjDDoKmvf9X_Q1lNE-UdhKScgHHImWIfesNlAw1MKvH99JTPkVqTutNXJOgE1C_0i1LjndvAC7EwOrzut2092zseeB57oUEBeWONwcxWgO6UWDuhmUpExL_3LXHoxsWxEDBYzNeS0LxeWxNmVZIbMq-lm1XHFfkRq8reXPsbdGgnmii9Cj47KRDTqZYeUe4ENDu9DJBxLuocBWDpLjBpMkTaqQq9MRBd9j2U571gA.Te2iJcx7TtblOCju9KC0zA3982_OHapFKW6dta5a8r4&dib_tag=se&keywords=vitamin+B3&qid=1718621682&sprefix=vitamin+b3%2Caps%2C203&sr=8-4";

// const divineBountySuperBcomplex = "https://www.amazon.com/Super-Complex-Vitamins-Supplement-Vegetarian/dp/B07414752B/ref=sr_1_4?crid=JBN0MFGHK3X2&dib=eyJ2IjoiMSJ9.9Z9dOHvFslhnaNDysP2LwG6zwpcDUSZuOmUClUDXgnvZppL1B4MSptQ2ItRDzaMykoq0rIaHDBFBOWavaqdgP-QKkKSpXoMlRD3bN5l-a8iMBw0GN92p1llOSwzPGmth2Gz-rdzudfyvEWoTDScbbL9nr_BLFCCWQ5H1B1QDXRKo2bCKTX9GonKGfvX8wadBAdYbFHhVZwtbJedVdCEgRJFim3NR2xTV-ZpADztIjoAg-vZUozlG6DHlkibNNx9weYYIgbvMkoz1vTDXmLZz_9urcS3xFw9aXnU__jDTU5k.NpUkRNNJZc4FY4ve55oAbNx5C3FaWQBVQAXbYmVdq1s&dib_tag=se&keywords=vitamin+B2&qid=1718621375&sprefix=vitamin+b2%2Caps%2C195&sr=8-4";
// const bronsonSuperBcomplex = "https://www.amazon.com/Bronson-Vitamin-Complex-Sustained-Release/dp/B0CT5Y3XK2/ref=sr_1_4?crid=1NPKMKYRTSY7W&dib=eyJ2IjoiMSJ9.m_TqrBrkrihtgJ2xMnA1_xHba7egjoUN3RxCCdSOmteiw3nW5uJcV7tdNo6HdRB-Q6gjDDoKmvf9X_Q1lNE-UdhKScgHHImWIfesNlAw1MKvH99JTPkVqTutNXJOgE1C_0i1LjndvAC7EwOrzut2092zseeB57oUEBeWONwcxWgO6UWDuhmUpExL_3LXHoxsWxEDBYzNeS0LxeWxNmVZIbMq-lm1XHFfkRq8reXPsbdGgnmii9Cj47KRDTqZYeUe4ENDu9DJBxLuocBWDpLjBpMkTaqQq9MRBd9j2U571gA.Te2iJcx7TtblOCju9KC0zA3982_OHapFKW6dta5a8r4&dib_tag=se&keywords=vitamin+B3&qid=1718621682&sprefix=vitamin+b3%2Caps%2C203&sr=8-4";
const NOWfoodVitaminB5 =
  "https://www.amazon.com/NOW-Pantothenic-Acid-500-Capsules/dp/B0013OUQEM/ref=sr_1_5?crid=28KGEZMWE39OQ&dib=eyJ2IjoiMSJ9.fNf6G2qo5KOqO2XaWYZAblZLrgwbAXtuTfToeSMyo9GXgP6IZ1d48JGuvTCgvIkQn07zLWWqQGEWm4AreFN3sUI9Qqon1RXBAFfTZ73qnZfXsi3Lc1Bk17uwpv0B84QxOvXgoLl31HhSkuvMgAodrjNyRnwsQz8dhxJAAInC84pQ7Ele3oeZER56UPark5VgUNrO3zJ7z2zvd877PO6bbi4GQNEBmHHcpbFKb1awvfa9DV-GOkm1Q20jtqTvlaLZf-zQuNImQtt5BJjXjIGHZjr-qwJRjsegNgkxkpdNB-0.J7LlWHRK1osF_GcN1sZ1E3iGFsYoweeK2H4bcmA0RWE&dib_tag=se&keywords=vitamin+B5&qid=1718621861&sprefix=vitamin+b5%2Caps%2C205&sr=8-5";

const NOWfoodVitaminB6 =
  "https://www.amazon.com/NOW-Vitamin-100mg-Capsules-Pack/dp/B001F0R94E/ref=sr_1_4?crid=MVOL9XWPNY57&dib=eyJ2IjoiMSJ9.L8zRDaGfEzqLimQwtj5I6REim_biCL06vVD6O2Gv18zBZ7bVFLSfAf0LrMvwr6HGSvyo4Q7-Nem_OA0Un8k23FSZlNtC0LLyMYP7NLy5j431mM5yShOJmnFZeLDdRONJroDBPHfLro4gd7PYdgrwG8F_RTwjVZhltlmx6B3DzrqsjS34s0ifMawpMfEJhuBG_jd3x30MlzQGSCjunWYB25fDB3wHHBCQpJ4EorFZgiXTw-PLT1JEOXtGakO6D4ip-L_5D5VqL1o-w8WJBJ9LP-9MuyVD0mQkKZMv23tOIgA.4-aDqZjIl1-GiOXKQSaAgliYpJ6zz-N_vrVn2XXwD2A&dib_tag=se&keywords=vitamin+B6&qid=1718621946&sprefix=vitamin+b6%2Caps%2C253&sr=8-4";
const bronsonVitaminB6 =
  "https://www.amazon.com/Vitamin-100-Premium-Supplement-Cardiovascular/dp/B0006ZNFK6/ref=sr_1_3?crid=MVOL9XWPNY57&dib=eyJ2IjoiMSJ9.L8zRDaGfEzqLimQwtj5I6REim_biCL06vVD6O2Gv18zBZ7bVFLSfAf0LrMvwr6HGSvyo4Q7-Nem_OA0Un8k23FSZlNtC0LLyMYP7NLy5j431mM5yShOJmnFZeLDdRONJroDBPHfLro4gd7PYdgrwG8F_RTwjVZhltlmx6B3DzrqsjS34s0ifMawpMfEJhuBG_jd3x30MlzQGSCjunWYB25fDB3wHHBCQpJ4EorFZgiXTw-PLT1JEOXtGakO6D4ip-L_5D5VqL1o-w8WJBJ9LP-9MuyVD0mQkKZMv23tOIgA.4-aDqZjIl1-GiOXKQSaAgliYpJ6zz-N_vrVn2XXwD2A&dib_tag=se&keywords=vitamin+B6&qid=1718621946&sprefix=vitamin+b6%2Caps%2C253&sr=8-3";

const divineBountySuperBcomplex =
  "https://www.amazon.com/Super-Complex-Vitamins-Supplement-Vegetarian/dp/B07414752B/ref=sr_1_4?crid=JBN0MFGHK3X2&dib=eyJ2IjoiMSJ9.9Z9dOHvFslhnaNDysP2LwG6zwpcDUSZuOmUClUDXgnvZppL1B4MSptQ2ItRDzaMykoq0rIaHDBFBOWavaqdgP-QKkKSpXoMlRD3bN5l-a8iMBw0GN92p1llOSwzPGmth2Gz-rdzudfyvEWoTDScbbL9nr_BLFCCWQ5H1B1QDXRKo2bCKTX9GonKGfvX8wadBAdYbFHhVZwtbJedVdCEgRJFim3NR2xTV-ZpADztIjoAg-vZUozlG6DHlkibNNx9weYYIgbvMkoz1vTDXmLZz_9urcS3xFw9aXnU__jDTU5k.NpUkRNNJZc4FY4ve55oAbNx5C3FaWQBVQAXbYmVdq1s&dib_tag=se&keywords=vitamin+B2&qid=1718621375&sprefix=vitamin+b2%2Caps%2C195&sr=8-4";
const bronsonSuperBcomplex =
  "https://www.amazon.com/Bronson-Vitamin-Complex-Sustained-Release/dp/B0CT5Y3XK2/ref=sr_1_4?crid=1NPKMKYRTSY7W&dib=eyJ2IjoiMSJ9.m_TqrBrkrihtgJ2xMnA1_xHba7egjoUN3RxCCdSOmteiw3nW5uJcV7tdNo6HdRB-Q6gjDDoKmvf9X_Q1lNE-UdhKScgHHImWIfesNlAw1MKvH99JTPkVqTutNXJOgE1C_0i1LjndvAC7EwOrzut2092zseeB57oUEBeWONwcxWgO6UWDuhmUpExL_3LXHoxsWxEDBYzNeS0LxeWxNmVZIbMq-lm1XHFfkRq8reXPsbdGgnmii9Cj47KRDTqZYeUe4ENDu9DJBxLuocBWDpLjBpMkTaqQq9MRBd9j2U571gA.Te2iJcx7TtblOCju9KC0zA3982_OHapFKW6dta5a8r4&dib_tag=se&keywords=vitamin+B3&qid=1718621682&sprefix=vitamin+b3%2Caps%2C203&sr=8-4";

const NOWfoodVitaminB12 =
  "https://www.amazon.com/NOW-Vitamin-Folic-Chewable-Lozenges/dp/B001B7NU6M/ref=sr_1_5?crid=60I6SCL7J9QX&dib=eyJ2IjoiMSJ9.8YX_ZOt-J9FXlT6rblvwDV8QEIoHTn1n0oJ4mjEKcdmll9DWZidtPAbzORX-a-yJGidqSduqylOAzydYflmI3CpTQqe6F2BoGzO0SfhIv0_bmFebcTuGjqxESh5iPJWIyygY3OWwMHWw7yKDeuydN_sDpQfvyXowVE6c7buGZSc3VdVv99oZZCTH7e4GyjxaRhuhA4TQXMsv8I-zlIePUZ7aK6Y0x9P_lo0NqshLZ_plod_nA5OI7Anjk6Ip3l6gcBbIzbYoBOMke4KCCggy6HRqqfdWjskkWjDZahKuIwM.bDJ9lSkh5bNhR66wFIoADAa4HviBf61ZcdCqmkDOlQE&dib_tag=se&keywords=vitamin+B12&qid=1718622301&sprefix=vitamin+b12%2Caps%2C198&sr=8-5";
const bronsonVitaminB12 =
  "https://www.amazon.com/Bronson-Vitamin-2500mcg-Release-Sublingual/dp/B00NQ8O8LU/ref=sr_1_15?crid=3EG2R516LGOKJ&dib=eyJ2IjoiMSJ9.EkGMmPllKn1s9e2xhvR4axoDZERZkmTbhxIQZ259ajBZ1PR3JqZ6Z0QuQBKbXmmD3NaQMQE8sCUHy15smp2DCVODQS-klLNPdlaL_FmM_f8w8sFSmLWxLtzk4VQgs5flltNJ9ufIazIzWSmGaDQ109XGA1Z6taf3T0Ia4EZaPmlv0oM-yczOFgbfgnmeC7b1wxB3U3uuDWAnPmVmbzsFdfFs4ui9OyTqkchLty_Gr_EWSk9dE1PB98OiIiOAor8FGMYimfmxueMzH8YaaUtR7bVr4XQqrUzdE09wHv1iimU.lu5mrVkoDxjE48zZgGt23SOJByRRz92cFgCjdBniL8w&dib_tag=se&keywords=vitamin+e&qid=1718624922&refinements=p_123%3A231615%7C313676&rnid=85457740011&s=hpc&sprefix=vitamin+e%2Caps%2C189&sr=1-15";

const NOWfoodVitaminD3K2 =
  "https://www.amazon.com/NOW-Vitamin-D-3-K-2-Capsules/dp/B0019QT9LA/ref=sr_1_19?crid=3ILAD78XD3R09&dib=eyJ2IjoiMSJ9.fcCOph2vvyv3oA1xQtK0ZnhlAkRYN0zMfxar7eBJz0i6qzXmZYPGi0HdboxAH4acg3rIsC7yR5o49xpvcXhza_EwayeiPKez4NBT0o5dSNq9jcYc2TnMI_cDRhcHhDasaIdHzxxkZkrm6vp2f10L6s2elmx2VMjpjkPmGSkn9hgpCnlRXdK_CzfeiEbCgowDE_GCip4WQ2as1izGYCIAstGMAv4e56KhOBqOR2eQC5VELcdbGWvmqoeaKVW6VnO7YzktAO-wNE7hmURwkB0_SIMvCsT17nb9BQIoKRVtQyg.vh1j2upxQPAzRARhp12UOfI8DJtUBPgh4FwzkCwFJHU&dib_tag=se&keywords=vitamin+k&qid=1718623169&sprefix=vitamin+k%2Caps%2C325&sr=8-19";
// const bronsonVitaminD3K2 = "https://www.amazon.com/Vitamin-K2-MK7-Supplement-Vegetarian/dp/B0771R5L28/ref=sr_1_4?crid=3ILAD78XD3R09&dib=eyJ2IjoiMSJ9.fcCOph2vvyv3oA1xQtK0ZnhlAkRYN0zMfxar7eBJz0i6qzXmZYPGi0HdboxAH4acg3rIsC7yR5o49xpvcXhza_EwayeiPKez4NBT0o5dSNq9jcYc2TnMI_cDRhcHhDasaIdHzxxkZkrm6vp2f10L6s2elmx2VMjpjkPmGSkn9hgpCnlRXdK_CzfeiEbCgowDE_GCip4WQ2as1izGYCIAstGMAv4e56KhOBqOR2eQC5VELcdbGWvmqoeaKVW6VnO7YzktAO-wNE7hmURwkB0_SIMvCsT17nb9BQIoKRVtQyg.vh1j2upxQPAzRARhp12UOfI8DJtUBPgh4FwzkCwFJHU&dib_tag=se&keywords=vitamin+k&qid=1718623364&sprefix=vitamin+k%2Caps%2C325&sr=8-4";

const NOWfoodVitaminC =
  "https://www.amazon.com/NOW-Supplements-Bioflavonoids-Antioxidant-Protection/dp/B000OSUE4U/ref=sr_1_1?crid=1DDO522348HOC&dib=eyJ2IjoiMSJ9.kZ7PU8ED_U_eNhRO4GHR2CsgZQjUub_n99OGP27yhDk.jNZMTebujoGupGsBc0ftl1Bd1oK2EcV9SfGpWhY5ulQ&dib_tag=se&keywords=vitamin%2Bc%2B1000mg&qid=1718623557&refinements=p_123%3A231615&rnid=85457740011&s=hpc&sprefix=vitamin%2Bc%2Caps%2C194&sr=1-1&th=1";
const amazonVitaminC =
  "https://www.amazon.com/Amazon-Elements-Vitamin-1000mg-Tablets/dp/B07122C9VC/ref=sr_1_5?crid=1DDO522348HOC&dib=eyJ2IjoiMSJ9.F2paMOAX-HTDbk1WdvlZVwccTty6o6it3v-O7FCHdPQ2DgyGg0ZXtlBZCL2Zjl0ZEaKlQmKyrij3s6S1iZqOi38JZ98cW_obqHl5Z6GpJoV57hSaafJmYQr13YXlytQEQCf1sQ1gYOYHqgeG3KJ22hMwvd3TbaOZ1Hx_0nsO_5H9FYUpXWba41ylL8YJF3rlV2Y0Qy4Kq06trYueBeXW4I3Qs_dodXpJYBR85ylVOnDim2bSQ9EAdENCYHQKcl1sFMqCcTZn8jAfMoP-kdffcJ85BkRuSbvoSyqTCyl1OOM.rZw0a0yB0Ad9qInzTof0ram7s8RpD0lUgWoniTO4d50&dib_tag=se&keywords=vitamin+c+1000mg&qid=1718623554&sprefix=vitamin+c%2Caps%2C194&sr=8-5";

const NOWfoodVitaminE =
  "https://www.amazon.com/Vitamin-E-400-IU-100-Softgels/dp/B07V6L8LL9/ref=sr_1_4?crid=3EG2R516LGOKJ&dib=eyJ2IjoiMSJ9.EkGMmPllKn1s9e2xhvR4axoDZERZkmTbhxIQZ259ajBZ1PR3JqZ6Z0QuQBKbXmmD3NaQMQE8sCUHy15smp2DCVODQS-klLNPdlaL_FmM_f8w8sFSmLWxLtzk4VQgs5flltNJ9ufIazIzWSmGaDQ109XGA1Z6taf3T0Ia4EZaPmlv0oM-yczOFgbfgnmeC7b1wxB3U3uuDWAnPmVmbzsFdfFs4ui9OyTqkchLty_Gr_EWSk9dE1PB98OiIiOAor8FGMYimfmxueMzH8YaaUtR7bVr4XQqrUzdE09wHv1iimU.lu5mrVkoDxjE48zZgGt23SOJByRRz92cFgCjdBniL8w&dib_tag=se&keywords=vitamin+e&qid=1718624859&refinements=p_123%3A231615%7C313676&rnid=85457740011&s=hpc&sprefix=vitamin+e%2Caps%2C189&sr=1-4";
const bronsonVitaminE =
  "https://www.amazon.com/Supplement-Tocopherol-Antioxidant-Protects-Radicals/dp/B0006ZRVXI/ref=sr_1_1?crid=3EG2R516LGOKJ&dib=eyJ2IjoiMSJ9.EkGMmPllKn1s9e2xhvR4axoDZERZkmTbhxIQZ259ajBZ1PR3JqZ6Z0QuQBKbXmmD3NaQMQE8sCUHy15smp2DCVODQS-klLNPdlaL_FmM_f8w8sFSmLWxLtzk4VQgs5flltNJ9ufIazIzWSmGaDQ109XGA1Z6taf3T0Ia4EZaPmlv0oM-yczOFgbfgnmeC7b1wxB3U3uuDWAnPmVmbzsFdfFs4ui9OyTqkchLty_Gr_EWSk9dE1PB98OiIiOAor8FGMYimfmxueMzH8YaaUtR7bVr4XQqrUzdE09wHv1iimU.lu5mrVkoDxjE48zZgGt23SOJByRRz92cFgCjdBniL8w&dib_tag=se&keywords=vitamin+e&qid=1718624922&refinements=p_123%3A231615%7C313676&rnid=85457740011&s=hpc&sprefix=vitamin+e%2Caps%2C189&sr=1-1";

const bronsonVitaminA =
  "https://www.amazon.com/Bronson-Vitamin-Supports-Reproduction-Softgels/dp/B0006ZUS92/ref=sr_1_4?crid=6WE94HGIC5AN&dib=eyJ2IjoiMSJ9.34AD7r3aO0HCyO2COKzKjZw1EfCO-02SMWJo5YfCieCbHdaE7K9zDEiqgU9zVG1Hw1ZmzYzHh8CQS1YnKQSnuLEB-uf_QDBLtL9QtZbIoprvCmq8W6OSjPeorO5FdcJdCRtMqSbm0C8fZUzSNzK_X2vxX4WDJfYeGrlGt2kU3s7-D8QhDIfW0256a74Pyu07iamVVY-8d7Rkrz7A9-J_aXKFIZJyyKClGivR5K2UUuFTzSEc4raSLVIOOTM6DsZWo1zPyVH4Cjqt17s-GnqY7ghsSd3SxwcLafCLjf79uF8.mW2Rpf87NKe5bGZvzHwD_DQ9uwthCw68YwCSHZul5Do&dib_tag=se&keywords=vitamin+a&qid=1718625175&sprefix=vitamin+a%2Caps%2C189&sr=8-4";
const wholeFoodsMarketVitaminA =
  "https://www.amazon.com/365-Everyday-Value-Vitamin-000/dp/B074H5BVMP/ref=sr_1_1_ffob_sspa?crid=6WE94HGIC5AN&dib=eyJ2IjoiMSJ9.34AD7r3aO0HCyO2COKzKjSwnX6Jo5t29MjzuorW0muM-c3ksNIHBDFBPX7-188IhJ4xQBbZ3x9s0WGbc3-PHE3zFvMsfhYfPF5HrCKzj9zbKmQ68NSwZRxHF7A4IQgK3i860MCoCiWNHZn2IiQkwgQ2BzFrXHWwjC_SyJhzyxN5CF-4i_scG5UrSJLofxWTkbtJCWLF3Vw04Us6ru1nRsbGi8yw-TsWg0aNEpyS8xhajbheKnT6W1Hb9pjpyyRUJPXMKg9VMk8AUFwCvSCqFHNSurGIpTnJxivWTQjZbzW4.YxxADrLZToYBp3YugSPuTMCRwRCk0tqs2-4PK5pftDw&dib_tag=se&keywords=vitamin+a&qid=1718625299&s=hpc&sprefix=vitamin+a%2Caps%2C189&sr=1-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1";

// const NOWfoodVitaminD3K2 = "https://www.amazon.com/NOW-Vitamin-D-3-K-2-Capsules/dp/B0019QT9LA/ref=sr_1_19?crid=3ILAD78XD3R09&dib=eyJ2IjoiMSJ9.fcCOph2vvyv3oA1xQtK0ZnhlAkRYN0zMfxar7eBJz0i6qzXmZYPGi0HdboxAH4acg3rIsC7yR5o49xpvcXhza_EwayeiPKez4NBT0o5dSNq9jcYc2TnMI_cDRhcHhDasaIdHzxxkZkrm6vp2f10L6s2elmx2VMjpjkPmGSkn9hgpCnlRXdK_CzfeiEbCgowDE_GCip4WQ2as1izGYCIAstGMAv4e56KhOBqOR2eQC5VELcdbGWvmqoeaKVW6VnO7YzktAO-wNE7hmURwkB0_SIMvCsT17nb9BQIoKRVtQyg.vh1j2upxQPAzRARhp12UOfI8DJtUBPgh4FwzkCwFJHU&dib_tag=se&keywords=vitamin+k&qid=1718623169&sprefix=vitamin+k%2Caps%2C325&sr=8-19";
const bronsonVitaminD3K2 =
  "https://www.amazon.com/Vitamin-K2-MK7-Supplement-Vegetarian/dp/B0771R5L28/ref=sr_1_4?crid=3ILAD78XD3R09&dib=eyJ2IjoiMSJ9.fcCOph2vvyv3oA1xQtK0ZnhlAkRYN0zMfxar7eBJz0i6qzXmZYPGi0HdboxAH4acg3rIsC7yR5o49xpvcXhza_EwayeiPKez4NBT0o5dSNq9jcYc2TnMI_cDRhcHhDasaIdHzxxkZkrm6vp2f10L6s2elmx2VMjpjkPmGSkn9hgpCnlRXdK_CzfeiEbCgowDE_GCip4WQ2as1izGYCIAstGMAv4e56KhOBqOR2eQC5VELcdbGWvmqoeaKVW6VnO7YzktAO-wNE7hmURwkB0_SIMvCsT17nb9BQIoKRVtQyg.vh1j2upxQPAzRARhp12UOfI8DJtUBPgh4FwzkCwFJHU&dib_tag=se&keywords=vitamin+k&qid=1718623364&sprefix=vitamin+k%2Caps%2C325&sr=8-4";

const GNComega369 =
  "https://www.amazon.com/GNC-Triple-Strength-Complex-Softgels/dp/B00HNQCFMU/ref=sr_1_3?crid=2HUG85E1BHQWW&dib=eyJ2IjoiMSJ9.cxIszA4y7a7aCbZglG6K8xlToFq2rhY7mrJSFRGUPb6IhuI_ShgNBJJ0kNdFAcZ5ei4zUSzdd5xYMo9mSB-WmERn4cwO3pMITxuCaY9a52pRr1WuXQaHfC0EiBuYstoGiYxGoECWhXKEMDkhJjKLvT7INZFiPzyoDJRhRfO7M58uZF6mJnS2NFA2_HGEFPcoLqo_wgg3J92nQwTFTFAbm3qI1IutLpbmlm4qoCIxAsCVfQET4egJAUWLlsosZucOIH-NncnbIY_hmsi7jbdJ0k9cJuD4ffNexB2y4bM_GvM.Y9nD1nWI9UoKDrzB7vCvCa1mJCR62Ef8InEOp31BFkY&dib_tag=se&keywords=omega+3&qid=1718625404&refinements=p_123%3A16349%7C197010&rnid=85457740011&s=hpc&sprefix=omega+3%2Caps%2C274&sr=1-3";
const nordicOmega3 =
  "https://www.amazon.com/Nordic-Naturals-Ultimate-Omega-SoftGels/dp/B0739KKHWL/ref=sr_1_3?crid=6C2M2AD44HIT&dib=eyJ2IjoiMSJ9.yDtTKxplmardFXKcK_O-IWQarCVubPA_wXXuPqVaFFtrfmRVmKBuP9uETixuA7AZ4g117UBCnm_2Kgg-9VJ1BYFaPiqNkPe4nbLj5_T5WmcZ2PKJnq7p1CX-clAR0cgHaik7Yf3jkNRFedjsRyNUumNlyQq-VO9PXb6rzgchq09LqUplB43kUEttwVXlGeeFLULi_GJSZYa34KjFWosr69vvIRoG87Akw2h0gdzPaPnJxlrt-TT1gmHk5p_4ikV5Vh2H97ZEfGbcJPyCirT0H9H764P2kRfvR0m8gB7UJxo.5IbM2SfAqj8Jj4j5ZB9y5jJcdlPqff57yhgkwjTu-5U&dib_tag=se&keywords=omega+3&qid=1718625541&sprefix=omega+3%2Caps%2C186&sr=8-3";

const NOWfoodZinc =
  "https://www.amazon.com/NOW-Zinc-Picolinate-50mg-Capsules/dp/B001CA6WNG/ref=sr_1_4?crid=3OCA8ULCKPA9O&dib=eyJ2IjoiMSJ9.Rhd4cy4m3poO6HCt8oav53p-Q_FW0An3Ye2PLdO-tgKhnxWSX346E_mueLi-BnJ_qc9LcqmPjFsTuaCCv7w-lK6ccSrzqtrzGJ4e4VXXYdMYJlH2l8KDGtma4-o9f8y5YecGle460ziBcdGTbgG4YhYuVZZLfFaL3AiA_0rh7JtWgLg36mpvG9R_LVS4MPAj12goI0EYVoVCPy4AGSF5CftPBdDyxImmapJpt7ruvn2vzDe2dHWZiSvfnI3WFUBBCWJAmCQ66mJgA6qSjt6RaBJCghR_1VUpHi-p5ibM5YY.NjB0a2ywzDijjrdTa6mdN38r1suxnuaZSSrb6WW8eOw&dib_tag=se&keywords=zinc&qid=1718701729&refinements=p_123%3A231615%7C313676&rnid=85457740011&s=hpc&sprefix=zinc%2Caps%2C194&sr=1-4&th=1";
const bronsonZinc =
  "https://www.amazon.com/Bronson-Coverage-Support-Supplement-Picolinate/dp/B0842XLCNF/ref=sr_1_2?crid=3OCA8ULCKPA9O&dib=eyJ2IjoiMSJ9.Rhd4cy4m3poO6HCt8oav53p-Q_FW0An3Ye2PLdO-tgKhnxWSX346E_mueLi-BnJ_qc9LcqmPjFsTuaCCv7w-lK6ccSrzqtrzGJ4e4VXXYdMYJlH2l8KDGtma4-o9f8y5YecGle460ziBcdGTbgG4YhYuVZZLfFaL3AiA_0rh7JtWgLg36mpvG9R_LVS4MPAj12goI0EYVoVCPy4AGSF5CftPBdDyxImmapJpt7ruvn2vzDe2dHWZiSvfnI3WFUBBCWJAmCQ66mJgA6qSjt6RaBJCghR_1VUpHi-p5ibM5YY.NjB0a2ywzDijjrdTa6mdN38r1suxnuaZSSrb6WW8eOw&dib_tag=se&keywords=zinc&qid=1718701818&refinements=p_123%3A231615%7C313676&rnid=85457740011&s=hpc&sprefix=zinc%2Caps%2C194&sr=1-2";

const bronsonSelenium =
  "https://www.amazon.com/Selenium-Immune-System-Thyroid-Prostate/dp/B004MNBMZS/ref=sr_1_1?crid=1R60481G0I1OQ&dib=eyJ2IjoiMSJ9.ogusLEm571Vzd_syJLLW7uOvsWhpx-r4mWnWjQHOWI5B1jwLhBBWig5ocux0DIQb62yfX-Z20y1KlwTCyS6w1OACkawAze3P6GTqAGWPJysk8jD8UxcTyR7DYshMPuSqV-C7tk9tdcLWf3rKIzY9y1EnU2NuNcwTSdbSIaCyNlRBvIplyKth6bkuOMCOnZr2nKdNfplcpED7TQx7I205IOkCY2r3aUupJ5MWWzx4C8AWl4PM3-Zc5Gy3SM3a-c2PJ9jpGLva2uw8Y0G5_QFx1KHbV1lz-mdfA8spf4cYVcE.lSJ4K1SR3DbE9jesdmNPft2o7xN0LWC_lgfR9Oc8_8M&dib_tag=se&keywords=selenium&qid=1718702560&sprefix=selenium%2Caps%2C330&sr=8-1&th=1";
const NOWfoodSelenium =
  "https://www.amazon.com/NOW-Foods-Selenium-200-VCaps/dp/B00SJKPBNY/ref=sr_1_3?crid=1R60481G0I1OQ&dib=eyJ2IjoiMSJ9.ogusLEm571Vzd_syJLLW7uOvsWhpx-r4mWnWjQHOWI5B1jwLhBBWig5ocux0DIQb62yfX-Z20y1KlwTCyS6w1OACkawAze3P6GTqAGWPJysk8jD8UxcTyR7DYshMPuSqV-C7tk9tdcLWf3rKIzY9y1EnU2NuNcwTSdbSIaCyNlRBvIplyKth6bkuOMCOnZr2nKdNfplcpED7TQx7I205IOkCY2r3aUupJ5MWWzx4C8AWl4PM3-Zc5Gy3SM3a-c2PJ9jpGLva2uw8Y0G5_QFx1KHbV1lz-mdfA8spf4cYVcE.lSJ4K1SR3DbE9jesdmNPft2o7xN0LWC_lgfR9Oc8_8M&dib_tag=se&keywords=selenium&qid=1718702665&sprefix=selenium%2Caps%2C330&sr=8-3";

// DO TUKA SUM

const amazonIron =
  "https://www.amazon.com/Amazon-Elements-Vegan-Capsules-supply/dp/B0714BPQGB/ref=sr_1_1_ffob_sspa?crid=BQ7JF5OVAQ52&dib=eyJ2IjoiMSJ9.PDkV-rmFOu7GjhwpsbDmvLQ13goUeWzZiNMLORz8BW99_W0wkP3jDnpv0By-Ii5QQmeOmSUNg2iPV6wzut_NGpz3kH1eyHnfOwMAVktnH5M4c1cFQUdPDCne7FqrCYzEX9R4o3fdEl9sY9yjoHwsYGPvUHanF6TfVmuknrtQiuBwMM9QIDLsi85rekmRz1jj2xDrg5b2n-65uYt8On47r5HMudra8NQEQQnorhiMupYYAQ_5qFKyGyL_coMU_jtDaBPySkUiRY-zdYS1RfBBocZaqss5TJIsupdhsebQNCw.CuEE0wfX9NZkCX47Sr-kvepgfwBLxT5qHnVD0LIOZs8&dib_tag=se&keywords=iron+supplement&qid=1718702737&sprefix=iron%2Caps%2C193&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1";

const MGsportMagnesium =
  "https://www.amazon.com/Absorption-Magnesium-Supports-Function-Vitamins/dp/B00OHRT7GA/ref=sr_1_2?crid=2HV9V2LXPJI0W&dib=eyJ2IjoiMSJ9.BsPJvgdoOO67WuE_-eHYBWVHY60XELk-dLFVwG33h7n1OiVxaZIIinl0qRjCVAGX8eRZ0ML_QI2NqTBRTgccnhxofSvUmdQZqQOdhAMEmaDvdoFxxDcvgM__0_jZB3qryblsK1C5ipMP_rqUnlQUWmixvn3lWxQBE9qEVdq-NwTe3QoQ3nFe9CrVWxwdN0fSJWGuQlsVhvGl1PCY74Fqh5BNqBxLnfuwvu1csYt1U1ojR8kIzvVO19v8xRsJ7CBlfFzIPvphaT_7MLdxAtO4tKXWnZ5hBxwMeS0_gBaYB9Q.E3CBsB4-AmY2K4EcZUgD0E3DWwrPDYpUkq5Vu92Xr6c&dib_tag=se&keywords=magnesium&qid=1718702803&sprefix=magnesium%2Caps%2C207&sr=8-2";
const NOWfoodMagnesium =
  "https://www.amazon.com/NOW-Magnesium-400mg-180-Capsules/dp/B00CPJEGMW/ref=sr_1_4?crid=2HV9V2LXPJI0W&dib=eyJ2IjoiMSJ9.BsPJvgdoOO67WuE_-eHYBWVHY60XELk-dLFVwG33h7n1OiVxaZIIinl0qRjCVAGX8eRZ0ML_QI2NqTBRTgccnhxofSvUmdQZqQOdhAMEmaDvdoFxxDcvgM__0_jZB3qryblsK1C5ipMP_rqUnlQUWmixvn3lWxQBE9qEVdq-NwTe3QoQ3nFe9CrVWxwdN0fSJWGuQlsVhvGl1PCY74Fqh5BNqBxLnfuwvu1csYt1U1ojR8kIzvVO19v8xRsJ7CBlfFzIPvphaT_7MLdxAtO4tKXWnZ5hBxwMeS0_gBaYB9Q.E3CBsB4-AmY2K4EcZUgD0E3DWwrPDYpUkq5Vu92Xr6c&dib_tag=se&keywords=magnesium&qid=1718702862&sprefix=magnesium%2Caps%2C207&sr=8-4";

const NOWfoodCalcium =
  "https://www.amazon.com/NowFoods-Calcium-Hydroxyapatite-Caps-Capsules/dp/B009K72RAA/ref=sr_1_1?crid=ISWUHLAQPOIX&dib=eyJ2IjoiMSJ9.4oED_uUpi3z8gcIO-Y8cwcmR2LbsuzbnkIACG-08rFhoNsNo3Ya3F8HxgZOf55iXtDjQbgM_sh7x_eGUGSyPVwoot8DHWLFdd99ZKzqZh2DojJbugSfzwOXZKQZv7pEVT1x46BKnnRvOF3oQnIgPK4x_WyiN3fqFxcNtRgJlUUzbL2Eko5yc8I1j27rY7BD_oh8Ub-tHAWB2TdQ3T5_XQnyb4teFCsXCOeunMRN-roS1ICJ1eIWipvVN491ydHUvf5k0nAmarMdyDAuvEP0dQvgRnHMJCHy-hqgTOcfLONc.AQyG08UyRxM5hpvwhg0yByqaDKsKIykjLcoGCbnVd4M&dib_tag=se&keywords=calcium+supplement&qid=1718705616&refinements=p_123%3A231615&rnid=85457740011&s=hpc&sprefix=ca%2Caps%2C187&sr=1-1";
const GNCcalcium =
  "https://www.amazon.com/GNC-Calcium-Plus-Magnesium-Vitamin/dp/B084Z2J9YF/ref=sr_1_7?crid=ISWUHLAQPOIX&dib=eyJ2IjoiMSJ9.9R8mXczqiA3ORT1ERVS5SImiWAvtwCVUajTzi-5YITf1n5wvAgrG73pFHSG5YIjfaoNhEWGwq8zgSs0lqNKpfqxk1vL5EGf3S5hpUSiGV82Mmn0wmDd08A2vgQmuXYGI7zDnpYMvIiwk5mlbag_YYS2npXWJ5d2phw1PglKXKtnkzd5GVqpSQ4cKQdnt5kqDGZWpNzcvi1QH-SSza4BxC24e4c7_qgY86_rmQAtyBMgbYm5CdF75zJALs2JK0tl_hVr0iGlerw2vVTK4IGUIAX5gjPnq0u5kc45gK6A4o3c.pz6vVdn5Mx4Gxmam3J___sMlIkrtjSA7Ek44mgFUCJM&dib_tag=se&keywords=calcium+supplement&qid=1718705728&sprefix=ca%2Caps%2C187&sr=8-7";

const NOWfoodPotassium =
  "https://www.amazon.com/Potassium-Citrate-180-Capsules-Pack/dp/B0041U2PTY/ref=sr_1_2?crid=G6ZPRU0MQIAG&dib=eyJ2IjoiMSJ9._rdYi3Uc4pb-jXRA49D00aDSEGGRweUL3u1UPPbOCOiDmwpYUMhh4_pu97UjmNcjsrs0oHhF6pA16sHEJmzt5ygcguqZw57nHau7QhyDOGayODEwuMzchP0_QrBPH84H5CDC_FL4VMZA6vgGCYdp_-bermPfvHhDH1aB4RToGwSbWFnC-adp1wQqh70vsyHDleWcOjetkB54XWROlFIj7itEoKt2dKxH1Dw1vjZuY6ZfJtdwstOlqAnw_WCtwxI08Yv5J2iNaRe2acXdxzIfmlb73rwUhpiaOazmeKjiR88.0RiZTaXPYBj1SHnfS3LviJ31co5SwKjodaZBcb_tm6o&dib_tag=se&keywords=potassium&qid=1718705912&sprefix=potassium%2Caps%2C218&sr=8-2";
const wholeFoodsMarketPotassium =
  "https://www.amazon.com/365-Everyday-Value-Potassium-99mg/dp/B074KLCGC7/ref=sr_1_1_ffob_sspa?crid=G6ZPRU0MQIAG&dib=eyJ2IjoiMSJ9._rdYi3Uc4pb-jXRA49D00aDSEGGRweUL3u1UPPbOCOiDmwpYUMhh4_pu97UjmNcjsrs0oHhF6pA16sHEJmzt5ygcguqZw57nHau7QhyDOGayODEwuMzchP0_QrBPH84H5CDC_FL4VMZA6vgGCYdp_-bermPfvHhDH1aB4RToGwSbWFnC-adp1wQqh70vsyHDleWcOjetkB54XWROlFIj7itEoKt2dKxH1Dw1vjZuY6ZfJtdwstOlqAnw_WCtwxI08Yv5J2iNaRe2acXdxzIfmlb73rwUhpiaOazmeKjiR88.0RiZTaXPYBj1SHnfS3LviJ31co5SwKjodaZBcb_tm6o&dib_tag=se&keywords=potassium&qid=1718706100&sprefix=potassium%2Caps%2C218&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1";

const JCiodine =
  "https://www.amazon.com/J-CROWS%C2%AE-Lugols-Solution-Iodine-2/dp/B001AEFM9Y/ref=sr_1_3?crid=3U6XF3YTD3MFD&dib=eyJ2IjoiMSJ9.AFV4egKNZcnrZ2xNZsOL9U1upJaGx8ZlqxYf-HeW_68NCEN3FX8gxXDrTzqM0XCDieef5bVk_UShLak6MOVHRpVNbhp48ZoSVCjvdS91MZSmNfZrNCYD1G88NNmxCewQSUV0B1gWNrESJfq9elTmFgqjWcPhn1_xbivOYUZ53bDZhPCsBIKmz1ycelVqHML4PBe34shyWrKG3cycqMJ3kvOD1qpPdMRoxi4cc7qyYNDYcz3OXr-RD76kefuN4wgY84EUWk2RR3hcjQDZTMqT5iT-aSzfFc0CYes9JFR7BDk.alc4bR-b9td3JaGdoWRLMftlpGyfhU6v5BYNRonu_7s&dib_tag=se&keywords=iodine&qid=1718708107&sprefix=iodine%2Caps%2C289&sr=8-3";

const Phosphorus =
  "https://www.amazon.com/Research-Phosphozyme-Phosphorous-Electrolytes-Production/dp/B074XQLRT3/ref=sr_1_1?crid=2QAPKFO76C0EL&dib=eyJ2IjoiMSJ9.xYfXmd013Nw14A9bJBdelov9GOXseH5JGWDbLY2uGi9JYugKnZpxYIDtEF7gOn0GuwBp8N__lJMelF__b4_rPIMqSN44_bK-256SxqtKDScnh2mHSQ-16vKl5GHWCz4qNflz5zJN4bPzwG4NQJ9tuzEVfGOYw4ldnCgAiSSzvJEBqo96WqVJQc764m_FzIs8LBk69x2_5_fPzVzjdo4j6jJVP4JpSZpI-zQKmDQ2Z4LxT8gsJc9b8NdZ8ZwTzpDv_mhcucrbDj7NvICzc51rQsZxHJH0IRMZwsbR_i2LXMk.LD_7LT6lQCC3AAypcvlWnYXDojDWwUd4Yz-ZJhX5FnU&dib_tag=se&keywords=phosphorus+supplements&qid=1718708610&sprefix=phospo%2Caps%2C221&sr=8-1";

const NOWfoodCoQ10 =
  "https://www.amazon.com/CoQ10-200mg-60-VegiCaps-Pack/dp/B0041U6TJG/ref=sr_1_4?crid=2K9L3RTFB8X5V&dib=eyJ2IjoiMSJ9.6SYHAAUgz4MF4UPknO1x4vDmClyqSZFOMvTNO0lv97v6OyV-duvL4y4ccZgUn_rLpemXtj8bAkBHOwqti4VRJIHAb95Th_FiGQx0M2ar05qdS77s4e1dZYBk52omb3wgEwipCqfn1W_0UH7bH4RniL4vVaEzX2yFZHqj1HLm6d2BSsHzmqx5cVyDkqfPAuIt9448YKNjZzpszqDZNCRBW8d6KIGKt_vxsPJUD0AnIhGOIf_Ar-wOc9usgj69kXm3HP9kERGvEA2sQdcLWGe_Z5NKoQuNFrGH-g_0MPNW6BU.UeLLBRNoexxcxdJtXFSiz_eFKVi8vsweMrERU4Ney5U&dib_tag=se&keywords=CoQ10&qid=1718977761&sprefix=coq10%2Caps%2C358&sr=8-4";
const natureMadeCoQ10 =
  "https://www.amazon.com/Nature-Made-CoQ10-Naturally-Orange/dp/B004M7ZIC2/ref=sr_1_2?crid=2K9L3RTFB8X5V&dib=eyJ2IjoiMSJ9.Vhx2Mjj1c6xnxBHIxHzDA640pjvpzrTfOVztgA-Qcbv9RG-Gv6_fog52rEgVNNFHPGTKmHsG-lkq6uk_SYFnyO0nSQUTHaxBh_L57AllN62KoctBXZQmj6prPKMHzBDfBPu0kmTNbO1S1-n8FI7edfDz4ZrfpAUFJQI-FTuJCEhDbpR_r-wRfLhMozuPV40tFKfYPmHAyY4fSPX5jLWPRcxMCaJPruHxq8E6xBWULuf3pj-yMdXGijooEdGh9nKYeSbO2YADJWxiF7cMkyOg_2K_dbAPBI97S2L6VGAWPk4.YheQsrfDcB6OWKUE6i3GlT1mOQQWD9IQ6aaoPUJDaqg&dib_tag=se&keywords=CoQ10&qid=1718977823&sprefix=coq10%2Caps%2C358&sr=8-2";

const NOWsportsPeaProtein =
  "https://www.amazon.com/NOW-Nutrition-Digested-Unflavored-12-Ounce/dp/B00JL6ZKFE/ref=sr_1_3?crid=7JKJG6G30P5G&dib=eyJ2IjoiMSJ9.7EXmykbRMMqXoNUzk5lVWwviPu538WQoJZix6av3WlYNr8egqM6KgtWqOceDrpquY0Df8dB1zS-bWC3MSzTIB-kJho7YTAf7ZJd967WGD7YTdStVEVrYvpPGnzz00-zR.MZdmcI6fsU8AGDoIGbU6CixygfV9XZkUWXJrkMU6OAg&dib_tag=se&keywords=optimum%2Bnutrition%2Bpea%2Bprotein&qid=1718980734&sprefix=pea%2Bprotein%2Bopti%2Caps%2C202&sr=8-3&th=1";

const plantFusionPeaProtein =
  "https://www.amazon.com/PlantFusion-Complete-Plant-Based-Protein-Non-GMO/dp/B0021FEMZG/ref=sr_1_2?crid=7JKJG6G30P5G&dib=eyJ2IjoiMSJ9.7EXmykbRMMqXoNUzk5lVWwviPu538WQoJZix6av3WlYNr8egqM6KgtWqOceDrpquY0Df8dB1zS-bWC3MSzTIB-kJho7YTAf7ZJd967WGD7YTdStVEVrYvpPGnzz00-zR.MZdmcI6fsU8AGDoIGbU6CixygfV9XZkUWXJrkMU6OAg&dib_tag=se&keywords=optimum+nutrition+pea+protein&qid=1718980827&sprefix=pea+protein+opti%2Caps%2C202&sr=8-2";

const NOWsportsEggProtein =
  "https://www.amazon.com/NOW-Nutrition-Protein-Unflavored-1-2-Pound/dp/B0013OXDBU/ref=sr_1_fkmr1_1?crid=7JKJG6G30P5G&dib=eyJ2IjoiMSJ9.qHtSdLcflY4AEaBdKh9hSJTtAhwgiMkIUdBge8olHu9TqtCJjIo4j7NQCH8SweIGjV2MMJr_DLHzNddqvasXXXyrafHnIphCCCnCKG1UCRpin2phqfIz6Z5PrPQmJbpi.-tTHKwmIsrubEGwMJJysoP4Oa9xcYpC9ptqgV_l-XH0&dib_tag=se&keywords=optimum%2Bnutrition%2Bpea%2Bprotein&qid=1718980827&sprefix=pea%2Bprotein%2Bopti%2Caps%2C202&sr=8-1-fkmr1&th=1";

const trueNutritionEggProtein =
  "https://www.amazon.com/True-Nutrition-Protein-Unflavored-Unsweetened/dp/B07R3FPP6D/ref=sr_1_1?crid=3HVOUKX3QENFX&dib=eyJ2IjoiMSJ9.wO6mnoXhEQwBpK7wl8hFxk9ZMeDgT9xUcZ-Z-Nw2KUo8cjtAD8Xg2ZdB-YjdrsSSBZZeEsbOUm1BdtjttWrlk_zqnYUYg1NuRbmXT9F4Nud4gFPjT0YTUYNHkukE4xut6da6lQx_UMDYsA0B5W5OGC6xxnxaBKm_IVwtzG0v8aSqo5Kf-ZFqoVaXvy1DJnWmzYitdOsNp0AUf3LRagRkdsgoYbP5uLdb3WN4-kDVxsiSSvwNir3TY8wwNbLjgWoHiK3WpP0tURKJ_cL2h_CfkL021Ewp4xNYTHxu1dk5lfM.4CdES_2cX1E3dBP3TJ-s55aojIOHYHfRW-IpGkePGFo&dib_tag=se&keywords=egg%2Bprotein&qid=1718981024&sprefix=egg%2Bprotein%2Caps%2C209&sr=8-1&th=1";

const trueNutritionBeefProtein =
  "https://www.amazon.com/True-Nutrition-Grass-Fed-Protein-Unflavored/dp/B01LX7B6TY/ref=sr_1_1?crid=268RK2WOMYZKS&dib=eyJ2IjoiMSJ9.KYJrrsehIcOC-crvIg-9Qxy90CID7Ro1Dqs0oIgcp5UZV1GQuzrdrJikdn3-Fi6kVi3zPwlvbRilx5P9Xu9uO4Xi2lFrwU1tIqVAtK03GPkfaiQMhj3LrIhHeX0yOqxh0rC4nyDYYB63tyQNd0XQg0NkcFCs_0nYu0Xo0QNMhPf01E5qWWZWP9Ut9203NUZcR77mfkEn6HZQ7E4BiLR8P7y8jiuBOnF5YmArL1luSrjV2aY0bP8fCTB35bIUR00nfQzlUF1IeNvtggiK5c6vBsolNiNtHtsWeF50ZhP2qGo.7aNsW0pZBcDrRZQkztN7kqir0M2Y6SxQJMnfWqPMMho&dib_tag=se&keywords=beef+protein+powder&qid=1718981283&sprefix=beef+protein%2Caps%2C209&sr=8-1";

const MuscleMedsBeefProtein =
  "https://www.amazon.com/MuscleMeds-Carnivor-Protein-Multivitamin-Chocolate/dp/B0D41122WK/ref=sr_1_5?crid=268RK2WOMYZKS&dib=eyJ2IjoiMSJ9.KYJrrsehIcOC-crvIg-9Qxy90CID7Ro1Dqs0oIgcp5UZV1GQuzrdrJikdn3-Fi6kVi3zPwlvbRilx5P9Xu9uO4Xi2lFrwU1tIqVAtK03GPkfaiQMhj3LrIhHeX0yOqxh0rC4nyDYYB63tyQNd0XQg0NkcFCs_0nYu0Xo0QNMhPf01E5qWWZWP9Ut9203NUZcR77mfkEn6HZQ7E4BiLR8P7y8jiuBOnF5YmArL1luSrjV2aY0bP8fCTB35bIUR00nfQzlUF1IeNvtggiK5c6vBsolNiNtHtsWeF50ZhP2qGo.7aNsW0pZBcDrRZQkztN7kqir0M2Y6SxQJMnfWqPMMho&dib_tag=se&keywords=beef+protein+powder&qid=1718981375&sprefix=beef+protein%2Caps%2C209&sr=8-5";

const soyProtein =
  "https://www.amazon.com/NOW-Foods-Organic-Textured-Granules/dp/B008A3IRG8/ref=sr_1_1?crid=96Z8HFJF39FI&dib=eyJ2IjoiMSJ9.2uR7YTjyGF6U1RyAOK87cr3pkgw9sabPmU7v43NkfmYYReIZMpvPq-RwkUfYcn2ifLjInSOQgwUC11phXOt6E-LUZh7RHqaNb5fzQEbybbpj0ppq201l3ZEcME0Irpn-3MXZ7svE7S-yY6X964OXR9U8Khz8so4lfwmTe4RmXp7ExLzQmM0KsY-kRbvE2wh7V1zKm7hEPiXgSpSZtwZiRBezucclEgoXDPiySfp08hRyEyCkN-FwKVgBPKMrUEO4r0sP_R91i71Q1RIcrRDfyNWs-Ahbzb9O0nl5wmMHC00.adAxrNaV1ssY0gHl7HLCrOmRUMNPfhK-2_mVdj0brDE&dib_tag=se&keywords=soy+protein+powder&qid=1718981522&sprefix=soy+protein+powder%2Caps%2C230&sr=8-1";

const bronsonCLA =
  "https://www.amazon.com/Supports-Management-Non-Stimulating-Conjugated-Linoleic/dp/B01MTJZNQF/ref=sr_1_1?crid=3EGFUIX33EY38&dib=eyJ2IjoiMSJ9.RtLDpUqQiD2bODtdgW4rrsJfSckjtVcQOAAJPY1TGqwJwVrGX9P5p7Vfg0Nh5P6EM4FjwoQA02UJbYLBB3-VuNHu4Xw9prAfFGrAoRPRsLzqtr_Rs-8bAh86BmnnyiTmDl9F8WwLK_5M9TBTcbwpgj13u_qExVYgGzGMIPxpYBUC6KPK5vLkJk4i-wLxYzcP7GeWeEUQIwQWsOv8wbU0t7Yiwt0AXtSB6rmRibcZRPIQmF2Nc8fZWqbgeqJ1xXK_20rAqB8mqgFloKggIEH3-g3d1JPaf-2HB68oaycItSg.KaEWDteyPIsU_hlrXl1f0MidcJh_6qfF97U1FHdln-g&dib_tag=se&keywords=cla&qid=1718994064&sprefix=cla+%2Caps%2C394&sr=8-1";
const allmaxCLA =
  "https://www.amazon.com/ALLMAX-Nutrition-Highest-Purity-Yield-Softgels/dp/B005MORS3Q/ref=sr_1_4?crid=3EGFUIX33EY38&dib=eyJ2IjoiMSJ9.RtLDpUqQiD2bODtdgW4rrsJfSckjtVcQOAAJPY1TGqwJwVrGX9P5p7Vfg0Nh5P6EM4FjwoQA02UJbYLBB3-VuNHu4Xw9prAfFGrAoRPRsLzqtr_Rs-8bAh86BmnnyiTmDl9F8WwLK_5M9TBTcbwpgj13u_qExVYgGzGMIPxpYBUC6KPK5vLkJk4i-wLxYzcP7GeWeEUQIwQWsOv8wbU0t7Yiwt0AXtSB6rmRibcZRPIQmF2Nc8fZWqbgeqJ1xXK_20rAqB8mqgFloKggIEH3-g3d1JPaf-2HB68oaycItSg.KaEWDteyPIsU_hlrXl1f0MidcJh_6qfF97U1FHdln-g&dib_tag=se&keywords=cla&qid=1718994144&sprefix=cla+%2Caps%2C394&sr=8-4";

export const supplements = [
  {
    id: 1,
    name: "Whey Protein",
    type: "Protein",
    subtype: "Whey",
    amazonLinks: [impactWhey, dymatizeIso100, goldStandardIso],
    bannerImage: [
      "/bannerImages/supplements/impactWhey.jpg",
      "/bannerImages/supplements/dymatizeIso100.jpg",
      "/bannerImages/supplements/goldStandardIso.jpg",
    ],
    goal: ["Muscle Growth", "Fat Loss"],
    description:
      "Whey protein is a complete protein containing all nine essential amino acids. It is quickly absorbed and helps in muscle protein synthesis. Whey protein is derived from milk during the cheese-making process. It is separated from the curds and then purified and dried into a powder. Natural food sources include dairy products like milk, cheese, and yogurt. In the human body, whey protein is rapidly digested, leading to a quick rise in amino acids in the bloodstream, which supports muscle repair and growth. Protein is more satiating than carbohydrates or fats, helping you feel fuller for longer and reducing overall calorie intake. Adequate protein intake is crucial for preserving lean muscle mass during weight loss, which helps maintain a higher metabolic rate.",
    benefits: "Supports muscle growth and repair.",
    bestTimeToTake: "Post-workout",
    sideEffects:
      "May cause digestive issues in lactose-intolerant individuals.",
    recommendedDose: "25-50 grams per day",
    maxDose: "Up to 2 grams per kilogram of body weight per day",
    interactions:
      "Whey protein might decrease how well some antibiotics work. To avoid this interaction, take antibiotics at least 2 hours before or 4-6 hours after whey protein.",
  },
  {
    id: 2,
    name: "BCAA",
    type: "Amino Acid",
    subtype: "BCAA",
    amazonLinks: [allmaxAminoCoreBCAA, ONaminoEnergy, EVLleucineFormulaBCAA],
    bannerImage: [
      "/bannerImages/supplements/allmaxAminoCoreBCAA.jpg",
      "/bannerImages/supplements/ONaminoEnergy.jpg",
      "/bannerImages/supplements/EVLleucineFormulaBCAA.jpg",
    ],
    goal: ["Muscle Recovery"],
    description:
      "Branched-chain amino acids (BCAAs) include leucine, isoleucine, and valine. They are essential for muscle repair and recovery. BCAAs are found in high-protein foods such as meat, dairy, and legumes. They are produced via fermentation of carbohydrates and other substrates using specific strains of bacteria. In the body, BCAAs are taken up directly by muscles, bypassing the liver, and play a critical role in protein synthesis and energy production during exercise.",
    benefits: "Helps reduce muscle soreness and promotes muscle recovery.",
    bestTimeToTake: "Before or after workouts",
    sideEffects:
      "Generally considered safe, but excessive use may cause fatigue.",
    recommendedDose: "5-10 grams per day",
    maxDose: "Up to 20 grams per day",
    interactions:
      "Medications for diabetes (Antidiabetes drugs) interacts with BRANCHED-CHAIN AMINO ACIDS (BCAA) BCAA supplements might lower blood sugar levels. Taking BCAAs along with diabetes medications might cause blood sugar to drop too low.",
  },
  {
    id: 3,
    name: "Multivitamin",
    type: "Vitamin",
    subtype: "Multivitamin",
    amazonLinks: [centrumMultivitaminForMen, centrumMultivitaminForWomen],
    bannerImage: [
      "/bannerImages/supplements/centrumMultivitaminForMen.jpg",
      "/bannerImages/supplements/centrumMultivitaminForWomen.jpg",
    ],
    goal: ["Immunity"],
    description:
      "A multivitamin supplement contains a combination of vitamins and minerals to support overall health and fill nutritional gaps. These vitamins and minerals are typically derived from both synthetic and natural sources. Food sources vary widely depending on the specific vitamins and minerals included. In the body, multivitamins support various biochemical processes, including energy production, immune function, and bone health.",
    benefits: "Supports overall health and immune function.",
    bestTimeToTake: "With meals",
    sideEffects:
      "High doses of certain vitamins can cause adverse effects, such as vitamin toxicity.",
    recommendedDose: "One serving per day as directed on the label",
    maxDose: "Do not exceed the recommended dose on the label",
    interactions:
      "If your brand of multivitamin also contains iron, avoid taking this product at the same time as antacids, bisphosphonates (for example, alendronate), levodopa, thyroid medications (for example, levothyroxine), or some antibiotics (for example, tetracyclines, quinolones such as ciprofloxacin)",
  },
  {
    id: 4,
    name: "Creatine Monohydrate",
    type: "Creatine",
    subtype: "Monohydrate",
    amazonLinks: [ONmicronizedCreatine, allmaxMicronizedCreatine],
    bannerImage: [
      "/bannerImages/supplements/ONmicronizedCreatine.jpg",
      "/bannerImages/supplements/allmaxMicronizedCreatine.jpg",
    ],
    goal: ["Brain Health", "Muscle Growth"],
    description:
      "Creatine monohydrate is one of the most researched supplements, known for its ability to increase muscle mass, strength, and exercise performance by improving ATP production. Creatine is naturally found in red meat and fish. It is synthesized from sarcosine and cyanamide in an industrial process. In the body, creatine is stored in muscles and used to rapidly produce ATP, the energy currency of the cell, during high-intensity, short-duration exercises.",
    benefits: "Increases muscle mass, strength, and exercise performance.",
    bestTimeToTake: "Before or after workouts",
    sideEffects:
      "May cause water retention and digestive issues in some people.",
    recommendedDose: "3-5 grams per day",
    maxDose: "Up to 10 grams per day in divided doses",
    interactions:
      "Taking creatine with non steroidal anti-inflammatory drugs (NSAIDs) may increase the risk of kidney damage. Using creatine along with any medication that affects the kidneys may raise the risk of kidney damage.Caffeine may make it hard for your body to use creatine, and taking creatine and caffeine may increase the risk of dehydration. Using creatine, caffeine, and ephedra (now banned in the U.S.) may increase the risk of stroke.",
  },
  {
    id: 5,
    name: "Vitamin D",
    type: "Vitamin",
    subtype: "D",
    amazonLinks: [NOWfoodVitaminD3K2, bronsonVitaminD3K2],
    bannerImage: [
      "/bannerImages/supplements/NOWfoodVitaminD3K2.jpg",
      "/bannerImages/supplements/bronsonVitaminD3K2.jpg",
    ],
    goal: ["Immunity", "Brain Health", "Thyroid Function"],
    description:
      "Vitamin D is essential for maintaining healthy bones, regulating calcium levels, and supporting immune function. It can be obtained from sun exposure, food, and supplements. Food sources include fatty fish, egg yolks, and fortified dairy products. Vitamin D supplements are typically made from lanolin (from sheep's wool) or lichen. In the body, vitamin D is converted to its active form, calcitriol, which helps absorb calcium and phosphorus from the gut.",
    benefits: "Supports bone health and immune system.",
    bestTimeToTake: "With meals, especially those containing fat",
    sideEffects: "High doses can lead to toxicity and hypercalcemia.",
    recommendedDose: "600-800 IU per day",
    maxDose: "4,000 IU per day",
    interactions:
      "Best taken with vitamin K to maintain good absorption. When taking larger doses of vitamin D avoid large doses of calcium",
  },
  {
    id: 6,
    name: "Casein Protein",
    type: "Protein",
    subtype: "Casein",
    amazonLinks: [dymatizeEliteCasein, allmaxCaseinFX, muscletechPhase8],
    bannerImage: [
      "/bannerImages/supplements/dymatizeEliteCasein.jpg",
      "/bannerImages/supplements/allmaxCaseinFX.jpg",
      "/bannerImages/supplements/muscletechPhase8.jpg",
    ],
    goal: "Lean Muscle",
    description:
      "Casein protein is a slow-digesting protein that provides a steady release of amino acids, making it ideal for nighttime use to prevent muscle breakdown during sleep. It is derived from milk through a process of curdling and separation. Natural food sources include dairy products like cheese and milk. In the body, casein forms a gel or clot in the stomach, slowing down gastric emptying and providing a sustained release of amino acids over several hours.",
    benefits:
      "Provides a slow release of amino acids, ideal for nighttime use.",
    bestTimeToTake: "Before bed",
    sideEffects:
      "May cause digestive issues in lactose-intolerant individuals.",
    recommendedDose: "20-40 grams per day",
    maxDose: "Up to 2 grams per kilogram of body weight per day",
    interactions:
      "Casein protein might decrease how well some antibiotics work. To avoid this interaction, take antibiotics at least 2 hours before or 4-6 hours after casein protein.",
  },
  {
    id: 7,
    name: "Zinc",
    type: "Mineral",
    subtype: "Zinc",
    amazonLinks: [NOWfoodZinc, bronsonZinc],
    bannerImage: [
      "/bannerImages/supplements/NOWfoodZinc.jpg",
      "/bannerImages/supplements/bronsonZinc.jpg",
    ],
    goal: ["Immunity", "Thyroid Function"],
    description:
      "Zinc is an essential mineral that supports immune function, DNA synthesis, and cellular metabolism. It is found in foods like meat, shellfish, legumes, and seeds. Zinc supplements are often made from zinc gluconate or zinc sulfate. In the body, zinc is involved in numerous enzymatic reactions, plays a role in protein synthesis, and helps maintain the integrity of the immune system.",
    benefits: "Supports immune function, wound healing, and protein synthesis.",
    bestTimeToTake: "With meals",
    sideEffects:
      "High doses can cause nausea, vomiting, and immune suppression.",
    recommendedDose: "8-11 mg per day",
    maxDose: "40 mg per day",
    interactions:
      "Best taken with copper to maintain balance. Avoid taking with high doses of calcium or iron, which can interfere with zinc absorption.",
  },
  {
    id: 8,
    name: "Selenium",
    type: "Mineral",
    subtype: "Selenium",
    amazonLinks: [bronsonSelenium, NOWfoodSelenium],
    bannerImage: [
      "/bannerImages/supplements/bronsonSelenium.jpg",
      "/bannerImages/supplements/NOWfoodSelenium.jpg",
    ],
    goal: ["Immunity", "Thyroid Function"],
    description:
      "Selenium is a trace mineral that is important for reproduction, thyroid gland function, DNA production, and protecting the body from oxidative damage and infection. Food sources include Brazil nuts, seafood, and organ meats. Selenium supplements are often made from sodium selenite or selenomethionine. In the body, selenium is incorporated into selenoproteins, which play critical roles in reproduction, thyroid hormone metabolism, and antioxidant defense systems.",
    benefits: "Supports immune function and antioxidant protection.",
    bestTimeToTake: "With meals",
    sideEffects:
      "High doses can lead to selenosis, causing gastrointestinal issues, hair loss, and neurological damage.",
    recommendedDose: "55 mcg per day",
    maxDose: "400 mcg per day",
    interactions:
      "Best taken with vitamin E for enhanced antioxidant effects. Avoid taking with high doses of zinc or iron, which can interfere with selenium absorption.",
  },
  {
    id: 9,
    name: "Vitamin C",
    type: "Vitamin",
    subtype: "C",
    amazonLinks: [NOWfoodVitaminC, amazonVitaminC],
    bannerImage: [
      "/bannerImages/supplements/NOWfoodVitaminC.jpg",
      "/bannerImages/supplements/amazonVitaminC.jpg",
    ],
    goal: ["Immunity"],
    description:
      "Vitamin C is a powerful antioxidant that supports immune function, collagen synthesis, and the absorption of iron from plant-based foods. It also helps protect cells from damage. Natural food sources include citrus fruits, berries, kiwi, bell peppers, and spinach. Vitamin C supplements are typically made from ascorbic acid. In the body, vitamin C acts as a cofactor in enzymatic reactions, aids in collagen formation, and enhances the immune system.",
    benefits:
      "Supports immune function, collagen synthesis, and antioxidant protection.",
    bestTimeToTake: "With meals",
    sideEffects:
      "High doses can cause gastrointestinal discomfort, including diarrhea and nausea.",
    recommendedDose: "75-90 mg per day",
    maxDose: "2,000 mg per day",
    interactions:
      "Best taken with iron to enhance absorption. Avoid taking with large doses of copper, which can interfere with vitamin C absorption.",
  },
  {
    id: 10,
    name: "Vitamin B12",
    type: "Vitamin",
    subtype: "B12",
    amazonLinks: [NOWfoodVitaminB12, bronsonVitaminB12],
    bannerImage: [
      "/bannerImages/supplements/NOWfoodVitaminB12.jpg",
      "/bannerImages/supplements/NOWfoodVitaminB12.jpg",
    ],
    goal: ["Brain Health", "Energy", "Immunity"],
    description:
      "Vitamin B12 is essential for red blood cell formation, DNA synthesis, and neurological function. It is commonly found in animal products, making supplementation important for vegetarians and vegans. Food sources include meat, fish, dairy, and eggs. Vitamin B12 supplements are often made through bacterial fermentation. In the body, B12 is necessary for the proper function of the brain and nerves, and for the formation of red blood cells.",
    benefits: "Supports red blood cell formation and neurological function.",
    bestTimeToTake: "With meals",
    sideEffects:
      "High doses are generally considered safe, but can cause acne and rosacea in some individuals.",
    recommendedDose: "2.4 mcg per day",
    maxDose:
      "No established upper limit, but high doses may cause side effects in some people",
    interactions:
      "Best taken with folate for better absorption. Avoid taking with high doses of vitamin C, which can degrade vitamin B12.",
  },
  {
    id: 11,
    name: "Vitamin E",
    type: "Vitamin",
    subtype: "E",
    amazonLinks: [NOWfoodVitaminE, bronsonVitaminE],
    bannerImage: [
      "/bannerImages/supplements/NOWfoodVitaminE.jpg",
      "/bannerImages/supplements/bronsonVitaminE.jpg",
    ],
    goal: ["Antioxidant", "Immunity", "Thyroid Function"],
    description:
      "Vitamin E is a fat-soluble antioxidant that helps protect cells from oxidative damage. It is important for immune function, skin health, and eye health. Food sources include nuts, seeds, spinach, and broccoli. Vitamin E supplements are often made from synthetic or natural tocopherols. In the body, vitamin E is incorporated into cell membranes, protecting them from oxidative damage.",
    benefits:
      "Supports immune function, skin health, and antioxidant protection.",
    bestTimeToTake: "With meals, especially those containing fat",
    sideEffects:
      "High doses can cause bleeding and increase the risk of hemorrhagic stroke.",
    recommendedDose: "15 mg per day",
    maxDose: "1,000 mg per day",
    interactions:
      "Best taken with selenium for enhanced antioxidant effects. Avoid taking with high doses of omega-3 fatty acids, which can increase bleeding risk.",
  },
  {
    id: 12,
    name: "Vitamin A",
    type: "Vitamin",
    subtype: "A",
    amazonLinks: [bronsonVitaminA, wholeFoodsMarketVitaminA],
    bannerImage: [
      "/bannerImages/supplements/bronsonVitaminA.jpg",
      "/bannerImages/supplements/wholeFoodsMarketVitaminA.jpg",
    ],
    goal: ["Vision", "Imunity"],
    description:
      "Vitamin A is essential for maintaining healthy vision, immune function, and skin health. It is found in both animal and plant foods, with beta-carotene being a notable plant source. Food sources include liver, fish, dairy products, and colorful fruits and vegetables. Vitamin A supplements are typically made from retinyl palmitate or beta-carotene. In the body, vitamin A is involved in the formation of rhodopsin, a pigment in the retina that is necessary for low-light vision.",
    benefits: "Supports vision, immune function, and skin health.",
    bestTimeToTake: "With meals, especially those containing fat",
    sideEffects:
      "High doses can lead to toxicity, causing symptoms such as headache, dizziness, and liver damage.",
    recommendedDose: "700-900 mcg per day",
    maxDose: "3,000 mcg per day",
    interactions:
      "Best taken with zinc for better absorption. Avoid taking with high doses of vitamin E, which can interfere with vitamin A absorption.",
  },
  {
    id: 13,
    name: "Carnitine",
    type: "Amino Acid",
    subtype: "Carnitine",
    amazonLinks: [NOWfoodCarnitine, NOWsportsCarnitine],
    bannerImage: [
      "/bannerImages/supplements/NOWfoodCarnitine.jpg",
      "/bannerImages/supplements/NOWsportsCarnitine.jpg",
    ],
    goal: ["Fat Loss", "Energy", "Heart Health", "Brain Health"],
    description:
      " L-carnitine is important for heart and brain function, muscle movement, and many other body processes. Carnitine is an amino acid derivative that plays a crucial role in the production of energy by transporting fatty acids into the mitochondria of cells. It is found in foods like meat, fish, and dairy products. Carnitine supplements are usually synthesized from lysine and methionine. In the body, carnitine is involved in the transport of long-chain fatty acids into the mitochondria, where they are oxidized for energy production.",
    benefits: "Supports fat metabolism and energy production.",
    bestTimeToTake: "Before exercise",
    sideEffects:
      "High doses can cause nausea, vomiting, and a fishy body odor.",
    recommendedDose: "500-2,000 mg per day",
    maxDose: "Up to 3,000 mg per day",
    interactions:
      "Best taken with carbohydrates for better absorption. Avoid taking with high doses of other amino acids, which can compete for absorption.",
  },
  {
    id: 14,
    name: "Glutamine",
    type: "Amino Acid",
    subtype: "Glutamine",
    amazonLinks: [allmaxGlutamine, GNCglutamine],
    bannerImage: [
      "/bannerImages/supplements/allmaxGlutamine.jpg",
      "/bannerImages/supplements/GNCglutamine.jpg",
    ],
    goal: ["Muscle Recovery", "Immunity"],
    description:
      "Glutamine is a conditionally essential amino acid that supports immune function, intestinal health, and muscle recovery. It is the most abundant amino acid in the body. Natural food sources include meat, fish, eggs, dairy products, and certain vegetables like cabbage and spinach. Glutamine supplements are often produced via fermentation of glucose by bacteria. In the body, glutamine serves as a fuel source for immune cells and enterocytes in the gut, and plays a role in protein and nucleotide synthesis.",
    benefits: "Supports immune function, gut health, and muscle recovery.",
    bestTimeToTake: "Post-workout or before bed",
    sideEffects: "High doses can cause gastrointestinal issues.",
    recommendedDose: "5-10 grams per day",
    maxDose: "Up to 40 grams per day in divided doses",
    interactions:
      "Best taken with BCAAs for better muscle recovery. Avoid taking with high doses of other amino acids, which can compete for absorption.",
  },
  {
    id: 15,
    name: "Collagen",
    type: "Protein",
    subtype: "Collagen",
    amazonLinks: [collagenBestForWomen, vitalProteinsCollagen],
    bannerImage: [
      "/bannerImages/supplements/collagenBestForWomen.jpg",
      "/bannerImages/supplements/vitalProteinsCollagen.jpg",
    ],
    goal: ["Join Health", "Skin Health", "Bone Health"],
    description:
      "Collagen is the most abundant protein in the body, providing structure to the skin, bones, tendons, and ligaments. Supplementing with collagen can support skin elasticity, joint health, and bone strength. Natural food sources include bone broth, chicken skin, and fish. Collagen supplements are typically made by hydrolyzing the collagen from animal bones and connective tissues. In the body, collagen is broken down into peptides and amino acids that support the body's natural collagen production.",
    benefits: "Supports skin health, joint health, and bone strength.",
    bestTimeToTake: "With meals",
    sideEffects:
      "Generally considered safe, but high doses may cause digestive discomfort.",
    recommendedDose: "10-20 grams per day",
    maxDose: "Up to 30 grams per day",
    interactions:
      "Best taken with vitamin C for better collagen synthesis. Avoid taking with high doses of calcium, which can interfere with collagen absorption.",
  },
  {
    id: 16,
    name: "Glucosamine",
    type: "Amino Acid",
    subtype: "Glucosamine",
    amazonLinks: [NOWfoodGlucosamine, EVLglucosamineFormula],
    bannerImage: [
      "/bannerImages/supplements/NOWfoodGlucosamine.jpg",
      "/bannerImages/supplements/EVLglucosamineFormula.jpg",
    ],
    goal: ["Joint Health"],
    description:
      "Glucosamine is a natural compound found in cartilage. It is commonly used to support joint health and may help reduce the symptoms of osteoarthritis. Natural food sources are limited, but it can be found in the shells of shellfish. Glucosamine supplements are usually made by extracting it from shellfish shells or by fermentation of grains like corn. In the body, glucosamine helps maintain the health of cartilage and is involved in the production of glycosaminoglycans, which are essential components of cartilage.",
    benefits: "Supports joint health and may reduce osteoarthritis symptoms.",
    bestTimeToTake: "With meals",
    sideEffects: "May cause mild digestive issues, such as nausea or diarrhea.",
    recommendedDose: "1,500 mg per day",
    maxDose: "2,000 mg per day",
    interactions:
      "Best taken with chondroitin for better joint support. Avoid taking with blood thinners, which can increase bleeding risk.",
  },
  {
    id: 17,
    name: "Omega-3",
    type: "Fatty Acid",
    subtype: "Omega-3",
    amazonLinks: [GNComega369, nordicOmega3],
    bannerImage: [
      "/bannerImages/supplements/GNComega369.jpg",
      "/bannerImages/supplements/nordicOmega3.jpg",
    ],
    goal: ["Heart Health", "Brain Health"],
    description:
      "Omega-3 fatty acids are essential fats that are important for heart, brain, and overall health. They are found in fatty fish, flaxseeds, chia seeds, and walnuts. Omega-3 supplements are often made from fish oil, krill oil, or algae oil. In the body, omega-3s are incorporated into cell membranes, contributing to anti-inflammatory processes and supporting cardiovascular health. Omega-3s help lower high triglyceride levels, reducing the risk of heart disease.  Omega-3s can help lower blood pressure by improving blood vessel function. They can help stabilize heart rhythms and prevent arrhythmias.",
    benefits:
      "Supports heart health, brain function, and reduces inflammation.",
    bestTimeToTake: "With meals",
    sideEffects:
      "High doses can cause blood thinning and gastrointestinal issues.",
    recommendedDose: "250-500 mg per day of combined EPA and DHA",
    maxDose: "Up to 3,000 mg per day of combined EPA and DHA",
    interactions:
      "Best taken with antioxidants like vitamin E for better stability. Avoid taking with blood thinners, which can increase bleeding risk.",
  },
  // {
  //   id: 18,
  //   name: "Fish Oil",
  //   type: "Fatty Acid",
  //   subtype: "Fish Oil",
  //   amazonLinks: [],
  //   bannerImage: ["/bannerImages/supplements/"],
  //   goal: ["Heart Health"],
  //   description:
  //     "Fish oil is rich in omega-3 fatty acids EPA and DHA, which support cardiovascular health, reduce inflammation, and improve brain function. It is derived from the tissues of oily fish like salmon, mackerel, and sardines. In the body, fish oil is used to produce signaling molecules called eicosanoids, which play various roles in inflammation and blood clotting.",
  //   benefits:
  //     "Supports heart health, brain function, and reduces inflammation.",
  //   bestTimeToTake: "With meals",
  //   sideEffects:
  //     "May cause fishy aftertaste, gastrointestinal issues, and increased bleeding risk.",
  //   recommendedDose: "250-500 mg per day of combined EPA and DHA",
  //   maxDose: "Up to 3,000 mg per day of combined EPA and DHA",
  //   interactions:
  //     "Best taken with antioxidants like vitamin E for better stability. Avoid taking with blood thinners, which can increase bleeding risk.",
  // },
  {
    id: 19,
    name: "Magnesium",
    type: "Mineral",
    subtype: "Magnesium",
    amazonLinks: [MGsportMagnesium, NOWfoodMagnesium],
    bannerImage: [
      "/bannerImages/supplements/MGsportMagnesium.jpg",
      "/bannerImages/supplements/NOWfoodMagnesium.jpg",
    ],
    goal: ["Muscle Function", "Brain Health", "Heart Health"],
    description:
      "Magnesium is an essential mineral involved in over 300 biochemical reactions in the body, including muscle function, nerve function, and energy production. It is found in green leafy vegetables, nuts, seeds, and whole grains. Magnesium supplements are typically made from magnesium oxide, citrate, or chloride. In the body, magnesium helps regulate muscle and nerve function, blood sugar levels, and blood pressure.",
    benefits:
      "Supports muscle and nerve function, energy production, and bone health.",
    bestTimeToTake: "With meals or before bed",
    sideEffects:
      "High doses can cause diarrhea, nausea, and abdominal cramping.",
    recommendedDose: "310-420 mg per day",
    maxDose: "350 mg per day from supplements",
    interactions:
      "Best taken with vitamin D for better absorption. Avoid taking with high doses of calcium, which can interfere with magnesium absorption.",
  },
  {
    id: 20,
    name: "Calcium",
    type: "Mineral",
    subtype: "Calcium",
    amazonLinks: [NOWfoodCalcium, GNCcalcium],
    bannerImage: [
      "/bannerImages/supplements/NOWfoodCalcium.jpg",
      "/bannerImages/supplements/GNCcalcium.jpg",
    ],
    goal: ["Bone Health"],
    description:
      "Calcium is essential for bone health, muscle function, and nerve transmission. It is found in dairy products, leafy green vegetables, and fortified foods. Calcium supplements are often made from calcium carbonate or calcium citrate. In the body, calcium is stored in bones and teeth, where it supports their structure and function. It also plays a role in muscle contraction, blood clotting, and nerve signaling.",
    benefits: "Supports bone health, muscle function, and nerve signaling.",
    bestTimeToTake: "With meals",
    sideEffects:
      "High doses can cause constipation, kidney stones, and impaired absorption of other minerals.",
    recommendedDose: "1,000-1,200 mg per day",
    maxDose: "2,500 mg per day",
    interactions:
      "Best taken with vitamin D for better absorption. Avoid taking with high doses of magnesium or iron, which can interfere with calcium absorption.",
  },
  {
    id: 21,
    name: "Iron",
    type: "Mineral",
    subtype: "Iron",
    amazonLinks: [amazonIron],
    bannerImage: ["/bannerImages/supplements/amazonIron.jpg"],
    goal: ["Energy", "Immunity"],
    description:
      "Iron is essential for the production of hemoglobin, which carries oxygen in the blood. It is found in red meat, poultry, seafood, beans, and fortified cereals. Iron supplements are typically made from ferrous sulfate or ferrous gluconate. In the body, iron is incorporated into hemoglobin and myoglobin, which are necessary for oxygen transport and storage in muscles.",
    benefits:
      "Supports oxygen transport, energy production, and immune function.",
    bestTimeToTake:
      "On an empty stomach or with vitamin C for better absorption",
    sideEffects:
      "High doses can cause gastrointestinal issues, including constipation and nausea.",
    recommendedDose: "8-18 mg per day",
    maxDose: "45 mg per day",
    interactions:
      "Best taken with vitamin C for better absorption. Avoid taking with calcium supplements, which can inhibit iron absorption.",
  },
  {
    id: 22,
    name: "CoQ10",
    type: "Antioxidant",
    subtype: "CoQ10",
    amazonLinks: [NOWfoodCoQ10, natureMadeCoQ10],
    bannerImage: [
      "/bannerImages/supplements/NOWfoodCoQ10.jpg",
      "/bannerImages/supplements/natureMadeCoQ10.jpg",
    ],
    goal: ["Heart Health"],
    description:
      "Coenzyme Q10 (CoQ10) is an antioxidant that supports energy production in cells and protects them from oxidative damage. It is found in small amounts in meat, fish, and whole grains. CoQ10 supplements are usually made from a fermentation process involving bacteria or yeast. In the body, CoQ10 is concentrated in the mitochondria, where it helps produce ATP, the primary energy carrier in cells.",
    benefits:
      "Supports heart health, energy production, and antioxidant protection.",
    bestTimeToTake: "With meals containing fat",
    sideEffects:
      "Generally considered safe, but high doses can cause gastrointestinal issues.",
    recommendedDose: "100-200 mg per day",
    maxDose: "Up to 1,200 mg per day",
    interactions:
      "Best taken with fat-containing meals for better absorption. Avoid taking with blood-thinning medications without consulting a doctor.",
  },
  {
    id: 23,
    name: "Vitamin K",
    type: "Vitamin",
    subtype: "K",
    amazonLinks: [NOWfoodVitaminD3K2, bronsonVitaminD3K2],
    bannerImage: [
      "/bannerImages/supplements/NOWfoodVitaminD3K2.jpg",
      "/bannerImages/supplements/bronsonVitaminD3K2.jpg",
    ],
    goal: ["Bone Health"],
    description:
      "Vitamin K is essential for blood clotting and bone health. It is found in leafy green vegetables, such as kale and spinach, and in fermented foods like natto. Vitamin K supplements are often made from synthetic menaquinone-7 (MK-7) or phylloquinone. In the body, vitamin K activates proteins involved in blood clotting and calcium metabolism.",
    benefits: "Supports blood clotting and bone health.",
    bestTimeToTake: "With meals containing fat",
    sideEffects: "High doses can interfere with anticoagulant medications.",
    recommendedDose: "90-120 mcg per day",
    maxDose:
      "No established upper limit, but high doses should be avoided without medical advice",
    interactions:
      "Best taken with vitamin D for better bone health. Avoid taking with high doses of vitamin E, which can interfere with vitamin K absorption.",
  },
  {
    id: 24,
    name: "Vitamin B1",
    type: "Vitamin",
    subtype: "B1 (Thiamine)",
    amazonLinks: [JamiesonVitaminB1, GNCVitaminB1],
    bannerImage: [
      "/bannerImages/supplements/JamiesonVitaminB1.jpg",
      "/bannerImages/supplements/GNCVitaminB1.jpg",
    ],
    goal: ["Energy"],
    description:
      "Vitamin B1 (thiamine) is essential for carbohydrate metabolism and nerve function. It is found in whole grains, pork, fish, and legumes. Thiamine supplements are typically made from synthetic thiamine mononitrate or thiamine hydrochloride. In the body, thiamine is converted to thiamine pyrophosphate, which acts as a coenzyme in energy metabolism.",
    benefits: "Supports energy production and nerve function.",
    bestTimeToTake: "With meals",
    sideEffects:
      "Generally considered safe, but very high doses can cause gastrointestinal issues.",
    recommendedDose: "1.1-1.2 mg per day",
    maxDose:
      "No established upper limit, but very high doses may cause side effects",
    interactions:
      "Best taken with other B vitamins for better absorption. Avoid taking with high doses of riboflavin, which can interfere with thiamine absorption.",
  },
  {
    id: 25,
    name: "Vitamin B2",
    type: "Vitamin",
    subtype: "B2 (Riboflavin)",
    amazonLinks: [NOWfoodVitaminB2, divineBountySuperBcomplex],
    bannerImage: [
      "/bannerImages/supplements/NOWfoodVitaminB2.jpg",
      "/bannerImages/supplements/divineBountySuperBcomplex.jpg",
    ],
    goal: ["Energy"],
    description:
      "Vitamin B2 (riboflavin) is important for energy production, cellular function, and metabolism of fats, drugs, and steroids. It is found in dairy products, eggs, lean meats, and green vegetables. Riboflavin supplements are typically made from synthetic riboflavin. In the body, riboflavin is converted to its active forms, FMN and FAD, which are essential for energy production and cellular function.",
    benefits: "Supports energy production and cellular function.",
    bestTimeToTake: "With meals",
    sideEffects:
      "High doses can cause bright yellow urine and, in rare cases, gastrointestinal issues.",
    recommendedDose: "1.1-1.3 mg per day",
    maxDose:
      "No established upper limit, but very high doses may cause side effects",
    interactions:
      "Best taken with other B vitamins for better absorption. Avoid taking with high doses of iron, which can interfere with riboflavin absorption.",
  },
  {
    id: 26,
    name: "Vitamin B3",
    type: "Vitamin",
    subtype: "B3 (Niacin)",
    amazonLinks: [NOWfoodVitaminB3, bronsonSuperBcomplex],
    bannerImage: [
      "/bannerImages/supplements/NOWfoodVitaminB3.jpg",
      "/bannerImages/supplements/bronsonSuperBcomplex.jpg",
    ],
    goal: ["Energy"],
    description:
      "Vitamin B3 (niacin) is important for energy production, DNA repair, and the metabolism of fats and cholesterol. It is found in meat, fish, poultry, and fortified cereals. Niacin supplements are typically made from synthetic niacin or niacinamide. In the body, niacin is converted to NAD and NADP, which are essential for energy production and cellular processes.",
    benefits:
      "Supports energy production, DNA repair, and cholesterol management.",
    bestTimeToTake: "With meals",
    sideEffects: "High doses can cause flushing, itching, and liver toxicity.",
    recommendedDose: "14-16 mg per day",
    maxDose: "35 mg per day",
    interactions:
      "Best taken with other B vitamins for better absorption. Avoid taking with alcohol, which can exacerbate side effects.",
  },
  {
    id: 27,
    name: "Vitamin B5",
    type: "Vitamin",
    subtype: "B5 (Pantothenic Acid)",
    amazonLinks: [NOWfoodVitaminB5],
    bannerImage: ["/bannerImages/supplements/NOWfoodVitaminB5.jpg"],
    goal: ["Energy"],
    description:
      "Vitamin B5 (pantothenic acid) is essential for the synthesis of coenzyme A, which is critical for fatty acid metabolism and energy production. It is found in meat, fish, eggs, and whole grains. Pantothenic acid supplements are typically made from synthetic calcium pantothenate. In the body, pantothenic acid is converted to coenzyme A, which is involved in the synthesis and oxidation of fatty acids.",
    benefits: "Supports energy production and fatty acid metabolism.",
    bestTimeToTake: "With meals",
    sideEffects:
      "Generally considered safe, but high doses can cause diarrhea and gastrointestinal issues.",
    recommendedDose: "5 mg per day",
    maxDose:
      "No established upper limit, but high doses may cause side effects",
    interactions:
      "Best taken with other B vitamins for better absorption. Avoid taking with high doses of biotin, which can interfere with pantothenic acid absorption.",
  },
  {
    id: 28,
    name: "Vitamin B6",
    type: "Vitamin",
    subtype: "B6 (Pyridoxine)",
    amazonLinks: [NOWfoodVitaminB6, bronsonVitaminB6],
    bannerImage: [
      "/bannerImages/supplements/NOWfoodVitaminB6.jpg",
      "/bannerImages/supplements/bronsonVitaminB6.jpg",
    ],
    goal: ["Brain Health"],
    description:
      "Vitamin B6 (pyridoxine) is important for brain health, protein metabolism, and the production of neurotransmitters. It is found in poultry, fish, potatoes, and non-citrus fruits. Pyridoxine supplements are typically made from synthetic pyridoxine hydrochloride. In the body, vitamin B6 is converted to its active form, pyridoxal 5'-phosphate, which is essential for enzyme reactions involved in metabolism.",
    benefits:
      "Supports brain health, protein metabolism, and neurotransmitter production.",
    bestTimeToTake: "With meals",
    sideEffects:
      "High doses can cause nerve damage and sensitivity to sunlight.",
    recommendedDose: "1.3-2.0 mg per day",
    maxDose: "100 mg per day",
    interactions:
      "Best taken with other B vitamins for better absorption. Avoid taking with high doses of magnesium, which can interfere with vitamin B6 absorption.",
  },
  {
    id: 29,
    name: "Vitamin B9",
    type: "Vitamin",
    subtype: "B9 (Folate)",
    amazonLinks: [bronsonSuperBcomplex, divineBountySuperBcomplex],
    bannerImage: [
      "/bannerImages/supplements/bronsonSuperBcomplex.jpg",
      "/bannerImages/supplements/divineBountySuperBcomplex.jpg",
    ],
    goal: ["Cell Growth", "Brain Health"],
    description:
      "Vitamin B9 (folate) is essential for DNA synthesis, cell growth, and the formation of red and white blood cells. It is found in leafy green vegetables, legumes, nuts, and fortified cereals. Folate supplements are typically made from synthetic folic acid. In the body, folate is converted to its active form, tetrahydrofolate, which is involved in one-carbon metabolism and DNA synthesis.",
    benefits: "Supports DNA synthesis, cell growth, and blood cell formation.",
    bestTimeToTake: "With meals",
    sideEffects:
      "High doses can mask vitamin B12 deficiency and cause digestive issues.",
    recommendedDose: "400 mcg per day",
    maxDose: "1,000 mcg per day from supplements",
    interactions:
      "Best taken with vitamin B12 for better absorption. Avoid taking with high doses of zinc, which can interfere with folic acid absorption.",
  },
  {
    id: 30,
    name: "Iodine",
    type: "Mineral",
    subtype: "Iodine",
    amazonLinks: [JCiodine],
    bannerImage: ["/bannerImages/supplements/JCiodine.jpg"],
    goal: ["Thyroid Function"],
    description:
      "Iodine is essential for the production of thyroid hormones, which regulate metabolism, growth, and development. It is found in iodized salt, seafood, dairy products, and seaweed. Iodine supplements are typically made from potassium iodide or sodium iodide. In the body, iodine is concentrated in the thyroid gland, where it is used to synthesize thyroid hormones.",
    benefits: "Supports thyroid function and metabolism.",
    bestTimeToTake: "With meals",
    sideEffects:
      "High doses can cause thyroid dysfunction and gastrointestinal issues.",
    recommendedDose: "150 mcg per day",
    maxDose: "1,100 mcg per day",
    interactions:
      "Best taken with selenium for better thyroid function. Avoid taking with high doses of other halogens (fluoride, bromide), which can interfere with iodine absorption.",
  },
  {
    id: 31,
    name: "Potassium",
    type: "Mineral",
    subtype: "Potassium",
    amazonLinks: [NOWfoodPotassium, wholeFoodsMarketPotassium],
    bannerImage: [
      "/bannerImages/supplements/NOWfoodPotassium.jpg",
      "/bannerImages/supplements/wholeFoodsMarketPotassium.jpg",
    ],
    goal: ["Electrolyte Balance", "muscle function", "Brain Health"],
    description:
      "Potassium is essential for maintaining electrolyte balance, muscle function, and nerve signaling. It is found in fruits (such as bananas and oranges), vegetables (such as potatoes and spinach), and dairy products. Potassium supplements are typically made from potassium chloride. In the body, potassium helps regulate fluid balance, muscle contractions, and nerve signals.",
    benefits:
      "Supports electrolyte balance, muscle function, and nerve signaling.",
    bestTimeToTake: "With meals",
    sideEffects:
      "High doses can cause hyperkalemia, leading to heart arrhythmias and muscle weakness.",
    recommendedDose: "2,500-3,000 mg per day",
    maxDose: "4,700 mg per day",
    interactions:
      "Best taken with magnesium for better electrolyte balance. Avoid taking with high doses of sodium, which can counteract potassium effects.",
  },
  {
    id: 32,
    name: "Phosphorus",
    type: "Mineral",
    subtype: "Phosphorus",
    amazonLinks: [Phosphorus],
    bannerImage: ["/bannerImages/supplements/Phosphorus.jpg"],
    goal: ["Bone Health", "Energy"],
    description:
      "Phosphorus is essential for the formation of bones and teeth, energy production, and cell membrane integrity. It is found in meat, fish, dairy products, and nuts. Phosphorus supplements are typically made from calcium phosphate or potassium phosphate. In the body, phosphorus is incorporated into bones and teeth and is a key component of ATP, the primary energy carrier in cells.",
    benefits:
      "Supports bone health, energy production, and cell membrane integrity.",
    bestTimeToTake: "With meals",
    sideEffects: "High doses can cause mineral imbalances and kidney damage.",
    recommendedDose: "700 mg per day",
    maxDose: "4,000 mg per day",
    interactions:
      "Best taken with vitamin D for better absorption. Avoid taking with high doses of calcium, which can interfere with phosphorus absorption.",
  },
  {
    id: 33,
    name: "Alanine",
    type: "Amino Acid",
    subtype: "Alanine",
    amazonLinks: [allmaxAlanine, GNCalanine],
    bannerImage: [
      "/bannerImages/supplements/allmaxAlanine.jpg",
      "/bannerImages/supplements/GNCalanine.jpg",
    ],
    goal: ["Muscle Recovery", "Energy"],
    description:
      "Alanine is a non-essential amino acid that plays a role in muscle protein synthesis and glucose metabolism. It is found in meat, poultry, fish, and dairy products. Alanine supplements are typically synthesized from natural sources through fermentation. In the body, alanine is involved in the glucose-alanine cycle, which helps maintain blood sugar levels during exercise.",
    benefits: "Supports muscle recovery and energy production.",
    bestTimeToTake: "Post-workout",
    sideEffects:
      "Generally considered safe, but high doses can cause gastrointestinal issues.",
    recommendedDose: "2-5 grams per day",
    maxDose:
      "No established upper limit, but high doses may cause side effects",
    interactions:
      "Best taken with carbohydrates for better absorption. Avoid taking with high doses of lysine, which can interfere with alanine absorption.",
  },
  {
    id: 34,
    name: "Arginine",
    type: "Amino Acid",
    subtype: "Arginine",
    amazonLinks: [NOWfoodArginine, drEmilArgininePlus],
    bannerImage: [
      "/bannerImages/supplements/NOWfoodArginine.jpg",
      "/bannerImages/supplements/drEmilArgininePlus.jpg",
    ],
    goal: ["Brain Health", "Muscle Growth", "Blood Flow"],
    description:
      "Arginine is a semi-essential amino acid that plays a role in nitric oxide production, which supports blood flow and cardiovascular health. It is found in meat, poultry, fish, and dairy products. Arginine supplements are typically synthesized from natural sources through fermentation. In the body, arginine is converted to nitric oxide, which helps relax blood vessels and improve circulation.",
    benefits:
      "Supports blood flow, cardiovascular health, and muscle performance.",
    bestTimeToTake: "Before exercise",
    sideEffects:
      "High doses can cause gastrointestinal issues and low blood pressure.",
    recommendedDose: "3-6 grams per day",
    maxDose: "Up to 10 grams per day",
    interactions:
      "Best taken with citrulline for enhanced nitric oxide production. Avoid taking with high doses of lysine, which can compete for absorption.",
  },
  {
    id: 35,
    name: "Leucine",
    type: "Amino Acid",
    subtype: "Leucine",
    amazonLinks: [EVLleucineFormulaBCAA, allmaxAminoCoreBCAA],
    bannerImage: [
      "/bannerImages/supplements/EVLleucineFormulaBCAA.jpg",
      "/bannerImages/supplements/allmaxAminoCoreBCAA.jpg",
    ],
    goal: ["Muscle Growth", "Muscle Recovery"],
    description:
      "Leucine is a branched-chain amino acid (BCAA) that plays a critical role in muscle protein synthesis and growth. It is found in meat, poultry, fish, and dairy products. Leucine supplements are typically made from the fermentation of natural sources like corn or soy. In the body, leucine activates the mTOR pathway, which stimulates muscle protein synthesis and helps build muscle mass.",
    benefits: "Supports muscle growth, recovery, and protein synthesis.",
    bestTimeToTake: "Post-workout or with meals",
    sideEffects:
      "High doses can cause gastrointestinal issues and an imbalance of other amino acids.",
    recommendedDose: "2-5 grams per day",
    maxDose: "Up to 10 grams per day",
    interactions:
      "Best taken with isoleucine and valine (other BCAAs) for balanced muscle growth. Avoid taking with high doses of tryptophan, which can compete for absorption.",
  },
  {
    id: 36,
    name: "Lysine",
    type: "Amino Acid",
    subtype: "Lysine",
    amazonLinks: [NOWfoodLysine, BronsonLysine],
    bannerImage: [
      "/bannerImages/supplements/NOWfoodLysine.jpg",
      "/bannerImages/supplements/BronsonLysine.jpg",
    ],
    goal: ["Immunity"],
    description:
      "Lysine is an essential amino acid that plays a role in protein synthesis, immune function, and calcium absorption. It is found in meat, poultry, fish, and dairy products. Lysine supplements are typically synthesized from natural sources through fermentation. In the body, lysine is involved in the production of collagen, enzymes, and antibodies.",
    benefits:
      "Supports immune function, collagen production, and calcium absorption.",
    bestTimeToTake: "With meals",
    sideEffects:
      "High doses can cause gastrointestinal issues and kidney problems.",
    recommendedDose: "1-3 grams per day",
    maxDose: "Up to 6 grams per day",
    interactions:
      "Best taken with vitamin C for better absorption. Avoid taking with high doses of arginine, which can interfere with lysine absorption.",
  },
  {
    id: 37,
    name: "Pea Protein",
    type: "Protein",
    subtype: "Pea Protein",
    amazonLinks: [NOWsportsPeaProtein, plantFusionPeaProtein],
    bannerImage: [
      "/bannerImages/supplements/NOWsportsPeaProtein.jpg",
      "/bannerImages/supplements/plantFusionPeaProtein.jpg",
    ],
    goal: ["Muscle Growth", "Muscle Recovery"],
    description:
      "Pea protein is a plant-based protein derived from yellow peas. It is an excellent source of protein for vegetarians and vegans. Pea protein supplements are typically made by isolating the protein from the peas through a process of milling, soaking, and drying. In the body, pea protein supports muscle growth and repair.",
    benefits: "Supports muscle growth, repair, and satiety.",
    bestTimeToTake: "Post-workout or as a meal replacement",
    sideEffects:
      "Generally considered safe, but high doses can cause bloating and gas.",
    recommendedDose: "20-30 grams per serving",
    maxDose:
      "No established upper limit, but high doses may cause side effects",
    interactions:
      "Best taken with vitamin C for better absorption. Avoid taking with high-calcium foods or supplements, which can inhibit protein absorption.",
  },
  {
    id: 38,
    name: "Beef Protein",
    type: "Protein",
    subtype: "Beef Protein",
    amazonLinks: [trueNutritionBeefProtein, MuscleMedsBeefProtein],
    bannerImage: [
      "/bannerImages/supplements/trueNutritionBeefProtein.jpg",
      "/bannerImages/supplements/MuscleMedsBeefProtein.jpg",
    ],
    goal: ["Muscle Growth", "Muscle Recovery"],
    description:
      "Beef protein is derived from beef and is a rich source of essential amino acids. It is an excellent alternative to whey protein for those who are lactose intolerant. Beef protein supplements are typically made by hydrolyzing beef into its constituent amino acids. In the body, beef protein supports muscle growth and repair.",
    benefits: "Supports muscle growth, repair, and recovery.",
    bestTimeToTake: "Post-workout or as a meal replacement",
    sideEffects:
      "Generally considered safe, but high doses can cause digestive issues.",
    recommendedDose: "20-30 grams per serving",
    maxDose:
      "No established upper limit, but high doses may cause side effects",
    interactions:
      "Best taken with carbohydrates for better absorption. Avoid taking with high-fiber foods, which can inhibit protein absorption.",
  },
  {
    id: 39,
    name: "Egg Protein",
    type: "Protein",
    subtype: "Egg Protein",
    amazonLinks: [NOWsportsEggProtein, trueNutritionEggProtein],
    bannerImage: [
      "/bannerImages/supplements/NOWsportsEggProtein.jpg",
      "/bannerImages/supplements/trueNutritionEggProtein.jpg",
    ],
    goal: ["Muscle Growth", "Muscle Recovery"],
    description:
      "Egg protein is derived from egg whites and is a highly bioavailable source of protein. It is an excellent option for those who are lactose intolerant or allergic to dairy. Egg protein supplements are typically made by separating the egg whites and drying them into a powder. In the body, egg protein supports muscle growth and repair.",
    benefits: "Supports muscle growth, repair, and satiety.",
    bestTimeToTake: "Post-workout or as a meal replacement",
    sideEffects:
      "Generally considered safe, but high doses can cause digestive issues.",
    recommendedDose: "20-30 grams per serving",
    maxDose:
      "No established upper limit, but high doses may cause side effects",
    interactions:
      "Best taken with vitamin B6 for better absorption. Avoid taking with biotin supplements, as raw egg whites contain avidin, which binds to biotin and inhibits its absorption.",
  },
  {
    id: 40,
    name: "Soy Protein",
    type: "Protein",
    subtype: "Soy Protein",
    amazonLinks: [soyProtein],
    bannerImage: ["/bannerImages/supplements/soyProtein.jpg"],
    goal: ["Muscle Growth", "Muscle Recovery"],
    description:
      "Soy protein is a plant-based protein derived from soybeans. It is an excellent source of protein for vegetarians and vegans. Soy protein supplements are typically made by isolating the protein from the soybeans through a process of washing, dehulling, and drying. In the body, soy protein supports muscle growth and repair.",
    benefits: "Supports muscle growth, repair, and heart health.",
    bestTimeToTake: "Post-workout or as a meal replacement",
    sideEffects:
      "Generally considered safe, but high doses can cause digestive issues and affect thyroid function.",
    recommendedDose: "20-30 grams per serving",
    maxDose:
      "No established upper limit, but high doses may cause side effects",
    interactions:
      "Best taken with vitamin D for better absorption. Avoid taking with high-fiber foods, which can inhibit protein absorption.",
  },
  {
    id: 41,
    name: "CLA",
    type: "Fatty Acid",
    subtype: "CLA (Conjugated Linoleic Acid)",
    amazonLinks: [allmaxCLA, bronsonCLA],
    bannerImage: [
      "/bannerImages/supplements/allmaxCLA.jpg",
      "/bannerImages/supplements/bronsonCLA.jpg",
    ],
    goal: ["Fat Loss"],
    description:
      "CLA (Conjugated Linoleic Acid) is a type of omega-6 fatty acid found naturally in meat and dairy products. It is known for its potential benefits in supporting weight management, reducing body fat, and preserving lean muscle mass. CLA supplements are typically derived from safflower oil or sunflower oil.",
    benefits:
      "Supports weight management, reduces body fat, and preserves lean muscle mass.",
    bestTimeToTake: "With meals",
    sideEffects:
      "May cause digestive issues such as diarrhea or nausea in some individuals.",
    recommendedDose: "3.2 grams per day for adults",
    maxDose: "Up to 6.4 grams per day",
    interactions:
      "Best taken with meals to enhance absorption. Avoid taking with high doses of omega-3 fatty acids, which can compete for absorption.",
  },
];
